// V3.0.9: Standard error codes
export const ERROR_CODES = {
  // 400 Bad Request
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_QUANTITY: 'INVALID_QUANTITY',

  // 401 Unauthorized
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // 403 Forbidden
  FORBIDDEN: 'FORBIDDEN',

  // 404 Not Found
  NOT_FOUND: 'NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',

  // 409 Conflict
  CONFLICT: 'CONFLICT',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT', // V3.0.9: Different body with same key
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS', // V3.0.9: Concurrent request still processing
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',

  // 422 Unprocessable
  UNPROCESSABLE: 'UNPROCESSABLE',
  PRODUCT_NOT_MAPPED: 'PRODUCT_NOT_MAPPED',

  // 500 Internal Error
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
