// V3.0.9: Standard error codes
// GO-LIVE-182: Extended with diagnostic error codes
export const ERROR_CODES = {
  // 400 Bad Request
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_QUANTITY: 'INVALID_QUANTITY',
  INVALID_FORMAT: 'INVALID_FORMAT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // 401 Unauthorized
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  // 403 Forbidden
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // 404 Not Found
  NOT_FOUND: 'NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // 408 Timeout
  TIMEOUT: 'TIMEOUT',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',

  // 409 Conflict
  CONFLICT: 'CONFLICT',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT', // V3.0.9: Different body with same key
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS', // V3.0.9: Concurrent request still processing
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // 422 Unprocessable
  UNPROCESSABLE: 'UNPROCESSABLE',
  PRODUCT_NOT_MAPPED: 'PRODUCT_NOT_MAPPED',

  // 429 Rate Limit
  RATE_LIMITED: 'RATE_LIMITED',

  // 500 Internal Error
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',

  // 503 Service Unavailable
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DEPENDENCY_UNAVAILABLE: 'DEPENDENCY_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
