#!/bin/bash
# GCP-STG-0641: Incident response runbook
echo "=== INCIDENT RESPONSE RUNBOOK ==="
echo ""
echo "SCENARIO 1: Database Down (Cloud SQL)"
echo "  Symptoms: 503 on all API endpoints, 'connection refused' in logs"
echo "  Steps:"
echo "    1. Check: gcloud sql instances describe supermandi-staging"
echo "    2. If stopped: gcloud sql instances patch supermandi-staging --activation-policy=ALWAYS"
echo "    3. If crashed: Check Cloud SQL logs in Console"
echo "    4. If connection limit: Reduce DB_POOL_MAX or restart instances"
echo "    5. Rollback: Restore from latest backup (GCP-STG-0595 script)"
echo ""
echo "SCENARIO 2: Redis Down (Memorystore)"
echo "  Symptoms: Rate limiting fails, sessions don't persist"
echo "  Steps:"
echo "    1. Check: gcloud redis instances describe supermandi-redis --region=asia-south1"
echo "    2. Backend gracefully degrades (in-memory fallback)"
echo "    3. If stuck: Restart Memorystore instance"
echo ""
echo "SCENARIO 3: Firebase Down"
echo "  Symptoms: Web portal OTP login fails, POS unaffected (custom OTP)"
echo "  Steps:"
echo "    1. Check: https://status.firebase.google.com"
echo "    2. POS: No impact (uses WhatsApp OTP)"
echo "    3. Web: Users can use password login fallback"
echo "    4. Wait for Firebase recovery"
echo ""
echo "SCENARIO 4: WhatsApp API Down"
echo "  Symptoms: POS OTP delivery fails, broadcast fails"
echo "  Steps:"
echo "    1. Check: Meta Business Suite status"
echo "    2. OTP fallback: Console log shows OTP (dev only)"
echo "    3. If SMS_DISABLED=false: SMS fallback auto-activates"
echo "    4. Notify operators: Use SuperAdmin manual enrollment"
echo ""
echo "SCENARIO 5: High 5xx Error Rate"
echo "  Symptoms: GCP-STG-0637 alert fires"
echo "  Steps:"
echo "    1. Check Cloud Run logs: Console → Cloud Run → Logs"
echo "    2. Recent deploy? Rollback: gcloud run services update-traffic main-backend --to-revisions=PREVIOUS=100"
echo "    3. Memory issue? Check metrics, increase to 1Gi"
echo "    4. DB connection spike? Check pool exhaustion"
echo ""
echo "ESCALATION:"
echo "  L1: Check dashboards + logs (5 min)"
echo "  L2: Rollback or restart (15 min)"
echo "  L3: Contact GCP support (if infrastructure issue)"
echo "=== RUNBOOK COMPLETE ==="
