#!/bin/bash
# GCP-STG-0687: API versioning strategy
#
# Documents the API versioning strategy for SuperMandi backend services.
# Covers when to create v2, URL path versioning, backward compatibility,
# deprecation headers, and client version negotiation.
#
# Usage:
#   bash scripts/docs/api-versioning-strategy.sh

set -euo pipefail

echo "=== API VERSIONING STRATEGY ==="
echo ""
echo "CURRENT STATE: All endpoints use /api/v1/ prefix"
echo "  Base URL: https://staging.supermandi.tech/api/v1/"
echo "  Gateway routes: backend/services/api-gateway/src/index.ts"
echo ""
echo "=== VERSIONING SCHEME: URL Path Versioning ==="
echo ""
echo "  Format: /api/v{major}/"
echo "  Example: /api/v1/catalog/products → /api/v2/catalog/products"
echo ""
echo "  Why URL path (not header-based):"
echo "    - Simple to understand and debug"
echo "    - Works in browser address bar"
echo "    - Easy to route at API Gateway / Cloud Run level"
echo "    - No hidden state in headers"
echo ""
echo "=== WHEN TO CREATE v2 ==="
echo ""
echo "  CREATE a new version (v2) when:"
echo "    - Removing a field from response body"
echo "    - Changing a field type (string to number, etc.)"
echo "    - Changing request body schema (removing required fields)"
echo "    - Changing authentication mechanism"
echo "    - Restructuring response envelope"
echo ""
echo "  DO NOT create a new version for:"
echo "    - Adding new optional fields to response"
echo "    - Adding new endpoints"
echo "    - Adding new query parameters"
echo "    - Bug fixes that correct behavior to match docs"
echo "    - Performance improvements"
echo ""
echo "=== BACKWARD COMPATIBILITY PERIOD ==="
echo ""
echo "  - Old version (v1) remains available for 6 months after v2 launch"
echo "  - During overlap period, both v1 and v2 are live"
echo "  - After 6 months, v1 returns 410 Gone with migration guide URL"
echo ""
echo "  Timeline example:"
echo "    Month 0: v2 launched, v1 still active"
echo "    Month 1-5: Both versions live, deprecation headers on v1"
echo "    Month 6: v1 returns 410 Gone"
echo ""
echo "=== DEPRECATION HEADERS ==="
echo ""
echo "  When v1 is deprecated (v2 exists), add these headers to v1 responses:"
echo ""
echo "    Deprecation: true"
echo "    Sunset: Sat, 01 Mar 2027 00:00:00 GMT"
echo "    Link: </api/v2/>; rel=\"successor-version\""
echo ""
echo "  Implementation in API Gateway:"
echo "    app.use('/api/v1', (req, res, next) => {"
echo "      if (V2_EXISTS) {"
echo "        res.set('Deprecation', 'true');"
echo "        res.set('Sunset', SUNSET_DATE);"
echo "        res.set('Link', '</api/v2/>; rel=\"successor-version\"');"
echo "      }"
echo "      next();"
echo "    });"
echo ""
echo "=== CLIENT VERSION NEGOTIATION ==="
echo ""
echo "  POS App:"
echo "    - App version determines API version"
echo "    - v1.x.x uses /api/v1/, v2.x.x uses /api/v2/"
echo "    - Force-update mechanism via app config endpoint"
echo "    - Config endpoint (/api/config) is version-independent"
echo ""
echo "  Web Portals:"
echo "    - Frontend build pins API version in environment variable"
echo "    - API_BASE_URL=https://staging.supermandi.tech/api/v1"
echo "    - New portal build deployed simultaneously with v2 backend"
echo ""
echo "  Migration path:"
echo "    1. Deploy v2 backend alongside v1"
echo "    2. Update web portals to use v2"
echo "    3. Release new POS app version targeting v2"
echo "    4. Monitor v1 traffic until it drops to zero"
echo "    5. After 6 months, sunset v1"
echo ""
echo "=== GATEWAY ROUTING ==="
echo ""
echo "  API Gateway routes by version prefix:"
echo "    /api/v1/* → main-backend (v1 handlers)"
echo "    /api/v2/* → main-backend (v2 handlers)"
echo ""
echo "  Each service registers versioned routes:"
echo "    router.get('/v1/catalog/products', v1Handler);"
echo "    router.get('/v2/catalog/products', v2Handler);"
echo ""
echo "Done."
