#!/bin/bash
# GCP-STG-0688: API response caching headers
#
# Documents the Cache-Control strategy for different API endpoint types.
# Proper caching headers reduce load on backend and improve client performance.
#
# Usage:
#   bash scripts/docs/api-caching-headers.sh

set -euo pipefail

echo "=== API RESPONSE CACHING HEADERS ==="
echo ""
echo "OVERVIEW"
echo "  Cache-Control headers tell clients and CDNs how long to cache responses."
echo "  Different endpoint types have different caching requirements."
echo ""
echo "=== CACHING STRATEGY BY ENDPOINT TYPE ==="
echo ""
echo "1. PRODUCT LISTS (public, max-age=60)"
echo "   Endpoints: GET /api/v1/catalog/products, GET /api/v1/catalog/categories"
echo "   Header: Cache-Control: public, max-age=60"
echo "   Reason: Product data changes infrequently (minutes, not seconds)."
echo "           60s cache reduces DB hits without stale data risk."
echo "   Example:"
echo "     res.set('Cache-Control', 'public, max-age=60');"
echo ""
echo "2. STORE CONFIG (private, max-age=300)"
echo "   Endpoints: GET /api/v1/platform/store/config, GET /api/v1/pos/config"
echo "   Header: Cache-Control: private, max-age=300"
echo "   Reason: Store config is per-store (private), changes rarely."
echo "           5-minute cache is safe. Private prevents CDN caching."
echo "   Example:"
echo "     res.set('Cache-Control', 'private, max-age=300');"
echo ""
echo "3. STATIC ASSETS (public, max-age=86400)"
echo "   Endpoints: /assets/*, /static/*, *.js, *.css (with content hash)"
echo "   Header: Cache-Control: public, max-age=86400, immutable"
echo "   Reason: Hashed filenames mean new content = new URL."
echo "           Safe to cache for 24 hours. Immutable prevents revalidation."
echo "   Note: Only use immutable for content-hashed filenames."
echo "   Example (nginx config):"
echo "     location /assets/ {"
echo "       add_header Cache-Control 'public, max-age=86400, immutable';"
echo "     }"
echo ""
echo "4. AUTH ENDPOINTS (no-store)"
echo "   Endpoints: POST /api/v1/auth/login, POST /api/v1/auth/refresh"
echo "   Header: Cache-Control: no-store"
echo "   Reason: Auth responses contain tokens — NEVER cache."
echo "           no-store prevents all caching (client, proxy, CDN)."
echo "   Example:"
echo "     res.set('Cache-Control', 'no-store');"
echo ""
echo "5. WRITE OPERATIONS (no-store)"
echo "   Endpoints: POST/PUT/DELETE on any resource"
echo "   Header: Cache-Control: no-store"
echo "   Reason: Mutation responses should not be cached."
echo ""
echo "6. USER-SPECIFIC DATA (private, no-cache)"
echo "   Endpoints: GET /api/v1/orders/mine, GET /api/v1/pos/shift"
echo "   Header: Cache-Control: private, no-cache"
echo "   Reason: User-specific, changes on every action."
echo "           no-cache forces revalidation on every request."
echo ""
echo "=== IMPLEMENTATION IN API GATEWAY ==="
echo ""
echo "  Add middleware in api-gateway to set default headers:"
echo ""
echo "  // Default: no caching for API responses"
echo "  app.use('/api/', (req, res, next) => {"
echo "    if (req.method !== 'GET') {"
echo "      res.set('Cache-Control', 'no-store');"
echo "    }"
echo "    next();"
echo "  });"
echo ""
echo "  Individual routes override with specific headers:"
echo "  // In catalog-service routes"
echo "  router.get('/products', (req, res) => {"
echo "    res.set('Cache-Control', 'public, max-age=60');"
echo "    // ... serve products"
echo "  });"
echo ""
echo "=== ADDITIONAL HEADERS ==="
echo ""
echo "  ETag: Use for conditional requests (If-None-Match)"
echo "  Vary: Accept-Encoding, Authorization"
echo "  X-Request-Id: Include for cache debugging"
echo ""
echo "Done."
