#!/bin/bash
# GCP-STG-0643: Capacity planning document
echo "=== CAPACITY PLANNING ==="
echo ""
echo "Current Config (Staging):"
echo "  Cloud Run: 512Mi × 1 CPU × 10 max instances"
echo "  Cloud SQL: db-g1-small (200 max connections)"
echo "  Redis: Memorystore basic (1GB)"
echo "  GCS: Standard storage"
echo ""
echo "Scaling Thresholds:"
echo "  | Metric | Current | Upgrade At | Action |"
echo "  |--------|---------|------------|--------|"
echo "  | Stores | 0 | 100 | Monitor |"
echo "  | Active POS devices | 0 | 500 | Increase max-instances to 20 |"
echo "  | Daily sales | 0 | 10,000 | Increase Cloud SQL tier |"
echo "  | Concurrent users | 0 | 200 | Increase memory to 1Gi |"
echo "  | Products per store | ~100 | 50,000 | Add read replica |"
echo "  | Firebase OTP/month | 0 | 10,000 | Upgrade to Blaze |"
echo "  | Voice commands/day | 0 | 5,000 | Monitor OpenAI costs |"
echo "  | GCS storage | ~0 | 100GB | Monitor costs |"
echo ""
echo "Cost Estimates (per month):"
echo "  | Component | 100 stores | 1,000 stores | 10,000 stores |"
echo "  |-----------|------------|--------------|---------------|"
echo "  | Cloud Run | \$50 | \$200 | \$1,000 |"
echo "  | Cloud SQL | \$30 | \$100 | \$500 |"
echo "  | Redis | \$30 | \$30 | \$100 |"
echo "  | Firebase OTP | \$0 | \$600 | \$18,000 |"
echo "  | WhatsApp OTP | \$0 | \$0 | \$0 |"
echo "  | OpenAI Voice | \$10 | \$100 | \$1,000 |"
echo "  | TOTAL | ~\$120 | ~\$1,030 | ~\$20,600 |"
echo ""
echo "Firebase OTP dominates cost at scale."
echo "Mitigation: Session persistence + migrate web to custom OTP."
echo "=== PLANNING COMPLETE ==="
