#!/bin/bash
# GCP-STG-0698: Multi-store — consolidated reporting across stores
set -euo pipefail
echo "=== MULTI-STORE: CONSOLIDATED REPORTING ==="
echo ""
echo "CONCEPT: Group-level dashboards aggregating all stores"
echo ""
echo "REPORTS:"
echo "  1. Group Sales Summary"
echo "     SELECT store_id, SUM(total) as revenue, COUNT(*) as transactions"
echo "     FROM orders.sales WHERE store_id IN (group stores)"
echo "     GROUP BY store_id"
echo ""
echo "  2. Group Stock Overview"
echo "     SELECT store_id, COUNT(DISTINCT product_id) as skus,"
echo "            SUM(current_qty) as total_units"
echo "     FROM inventory.stock_balances WHERE store_id IN (group stores)"
echo "     GROUP BY store_id"
echo ""
echo "  3. Group P&L"
echo "     Revenue - COGS - operational costs per store + group total"
echo ""
echo "  4. Comparative Analysis"
echo "     Store-vs-store performance (sales/sqft, inventory turns)"
echo ""
echo "ACCESS CONTROL:"
echo "  - Group owner sees all stores"
echo "  - Store manager sees only their store"
echo "  - SuperAdmin sees all groups"
echo ""
echo "IMPLEMENTATION: New /retailer-admin/group/reports/* endpoints"
echo "=== FEATURE DESIGN COMPLETE ==="
