#!/bin/bash
# GCP-STG-0644: Disaster recovery plan for asia-south1 outage
echo "=== DISASTER RECOVERY PLAN ==="
echo ""
echo "RPO (Recovery Point Objective): 1 hour"
echo "RTO (Recovery Time Objective): 4 hours"
echo ""
echo "TIER 1: Cloud Run Service Failure (RTO: 5 min)"
echo "  - Auto-healed by Cloud Run (restarts failed instances)"
echo "  - Min-instances=1 ensures always-warm"
echo "  - If persistent: rollback to previous revision"
echo ""
echo "TIER 2: Cloud SQL Failure (RTO: 1 hour)"
echo "  - Automated backups: daily (configured in GCP)"
echo "  - Point-in-time recovery: up to 7 days"
echo "  - Restore: gcloud sql backups restore BACKUP_ID --restore-instance=supermandi-staging"
echo "  - Cross-region: Create read replica in asia-south2 (Mumbai backup)"
echo ""
echo "TIER 3: Regional Outage (RTO: 4 hours)"
echo "  - Full asia-south1 (Mumbai) outage is extremely rare"
echo "  - Recovery steps:"
echo "    1. Restore Cloud SQL backup to asia-south2"
echo "    2. Deploy Cloud Run services to asia-south2"
echo "    3. Update DNS (Cloud DNS → new region)"
echo "    4. Update Memorystore (new Redis in asia-south2)"
echo "    5. Verify all services"
echo ""
echo "TIER 4: Data Loss (RTO: depends)"
echo "  - Cloud SQL: Restore from backup + transaction log replay"
echo "  - GCS: Cross-region replication (if configured)"
echo "  - Redis: Ephemeral data only (rate limits, cache) — auto-rebuilds"
echo ""
echo "TESTING:"
echo "  - Quarterly: Restore backup to test instance, verify data integrity"
echo "  - Annually: Full DR drill (simulate regional failover)"
echo "=== DR PLAN COMPLETE ==="
