#!/bin/bash
# GCP-STG-0697: Multi-store — inter-store stock transfer
set -euo pipefail
echo "=== MULTI-STORE: STOCK TRANSFER ==="
echo ""
echo "CONCEPT: Transfer inventory between stores in same group"
echo ""
echo "FLOW:"
echo "  1. Source store manager initiates transfer request"
echo "  2. Select products + quantities to transfer"
echo "  3. System creates TRANSFER_OUT ledger entry (source) + TRANSFER_IN (destination)"
echo "  4. Destination store manager confirms receipt (like GRN)"
echo "  5. Stock balances updated atomically in transaction"
echo ""
echo "LEDGER ENTRIES:"
echo "  Source:  delta_qty = -N, reason = 'TRANSFER_OUT', ref = transfer_id"
echo "  Dest:    delta_qty = +N, reason = 'TRANSFER_IN', ref = transfer_id"
echo ""
echo "NEW TABLE: inventory.stock_transfers"
echo "  (id, source_store_id, dest_store_id, status, items JSONB,"
echo "   initiated_by, confirmed_by, created_at, confirmed_at)"
echo ""
echo "STATUS FLOW: INITIATED → IN_TRANSIT → CONFIRMED / REJECTED"
echo ""
echo "GUARD: Both stores must be in same store_group"
echo "GUARD: Source store must have sufficient stock"
echo "GUARD: Atomic transaction (both ledger entries or neither)"
echo "=== FEATURE DESIGN COMPLETE ==="
