#!/bin/bash
# GCP-STG-0696: Multi-store — store group concept
set -euo pipefail
echo "=== MULTI-STORE: STORE GROUPS ==="
echo ""
echo "CONCEPT: One retailer owns multiple stores (chain stores)"
echo ""
echo "CURRENT STATE:"
echo "  - auth.users has one-to-many relationship with stores via auth.store_users"
echo "  - A user CAN be linked to multiple stores (role per store)"
echo "  - POS device is bound to ONE store (pos_devices.store_id)"
echo "  - Retailer web shows stores linked to logged-in user"
echo ""
echo "IMPLEMENTATION (Post-Launch):"
echo "  1. New table: platform.store_groups (id, name, owner_user_id, created_at)"
echo "  2. Add: platform.stores.group_id FK → store_groups.id"
echo "  3. Retailer web: Group dashboard showing all stores"
echo "  4. POS: Switch store without re-enrollment (if user has access)"
echo "  5. SuperAdmin: Group management + bulk operations"
echo ""
echo "DATA MODEL:"
echo "  store_groups (1) ──→ (N) stores"
echo "  users (1) ──→ (N) store_users ──→ (N) stores"
echo ""
echo "MIGRATION: Add group_id column to platform.stores (nullable, backward compatible)"
echo "=== FEATURE DESIGN COMPLETE ==="
