#!/bin/bash
# GCP-STG-0593: PhonePe API integration documentation
#
# Documents PhonePe B2B payment integration for SuperMandi POS.
# This is a POST-LAUNCH feature — implement when PhonePe partnership
# is established and merchant credentials are available.
#
# Usage:
#   bash scripts/docs/phonepe-integration.sh

set -euo pipefail

echo "=== PHONEPE B2B PAYMENT INTEGRATION ==="
echo ""
echo "STATUS: POST-LAUNCH — Implement after PhonePe partnership is established"
echo ""
echo "=== OVERVIEW ==="
echo "  PhonePe provides UPI-based B2B payment collection for kirana stores."
echo "  Integration allows customers to pay via PhonePe QR or app-to-app."
echo ""
echo "=== SDK SETUP ==="
echo ""
echo "  1. Register as PhonePe merchant at https://business.phonepe.com"
echo "  2. Obtain credentials:"
echo "     - PHONEPE_MERCHANT_ID: Assigned by PhonePe"
echo "     - PHONEPE_SALT_KEY: For request signing"
echo "     - PHONEPE_SALT_INDEX: Key index (typically 1)"
echo "  3. Install SDK (React Native):"
echo "     npm install phonepe-pg-sdk-react-native"
echo "  4. Add to environment variables:"
echo "     PHONEPE_MERCHANT_ID=MERCHANTXXXX"
echo "     PHONEPE_SALT_INDEX=1"
echo "     PHONEPE_ENV=PRODUCTION  # or SANDBOX for testing"
echo ""
echo "=== MERCHANT ID CONFIGURATION ==="
echo ""
echo "  Store in GCP (not in code):"
echo "    gcloud secrets create phonepe-merchant-id --data-file=- <<< MERCHANTXXXX"
echo "    gcloud secrets create phonepe-salt-key --data-file=- <<< key-value"
echo ""
echo "  Backend reads from environment:"
echo "    const merchantId = process.env.PHONEPE_MERCHANT_ID;"
echo ""
echo "=== PAYMENT INITIATION FLOW ==="
echo ""
echo "  1. POS creates order with amount"
echo "  2. POS calls backend: POST /api/v1/payments/phonepe/initiate"
echo "     Body: { orderId, amount, customerPhone }"
echo "  3. Backend creates PhonePe payment request:"
echo "     - Generate unique transactionId"
echo "     - Create payload with merchantId, amount, redirectUrl"
echo "     - Sign with SHA256(payload + saltKey) + ### + saltIndex"
echo "  4. Backend returns paymentUrl or QR data to POS"
echo "  5. POS opens PhonePe app or displays QR code"
echo "  6. Customer completes payment in PhonePe"
echo "  7. PhonePe calls callback URL with payment status"
echo ""
echo "=== CALLBACK URL ==="
echo ""
echo "  Configure in PhonePe dashboard:"
echo "    Callback URL: https://staging.supermandi.tech/api/v1/payments/phonepe/callback"
echo ""
echo "  Backend callback handler:"
echo "    - Verify signature (SHA256 check)"
echo "    - Update order payment status"
echo "    - Mark sale as PAID in orders.sales"
echo "    - Return 200 OK to PhonePe"
echo ""
echo "=== REFUND API ==="
echo ""
echo "  POST /api/v1/payments/phonepe/refund"
echo "  Body: { originalTransactionId, refundAmount, reason }"
echo ""
echo "  PhonePe refund API:"
echo "    POST https://api.phonepe.com/apis/hermes/pg/v1/refund"
echo "    - Full or partial refund supported"
echo "    - Refund credited within 5-7 business days"
echo "    - Track refund status via status check API"
echo ""
echo "=== TESTING ==="
echo ""
echo "  1. Use SANDBOX environment during development"
echo "  2. PhonePe provides test merchant credentials"
echo "  3. Test with PhonePe simulator app"
echo "  4. Verify callback handling with test transactions"
echo ""
echo "=== IMPLEMENTATION CHECKLIST ==="
echo "  [ ] PhonePe partnership agreement signed"
echo "  [ ] Merchant credentials obtained"
echo "  [ ] Backend payment endpoints created"
echo "  [ ] POS PhonePe payment flow implemented"
echo "  [ ] Callback signature verification"
echo "  [ ] Refund flow implemented"
echo "  [ ] Sandbox testing complete"
echo "  [ ] Production go-live with PhonePe"
echo ""
echo "Done."
