#!/bin/bash
# GCP-STG-0594: PineLabs POS terminal integration documentation
#
# Documents PineLabs hardware terminal integration for stores with
# PineLabs POS devices. This is for card payment acceptance via
# physical terminals paired with the SuperMandi POS app.
#
# Usage:
#   bash scripts/docs/pinelabs-integration.sh

set -euo pipefail

echo "=== PINELABS POS TERMINAL INTEGRATION ==="
echo ""
echo "STATUS: POST-LAUNCH — For stores with PineLabs hardware terminals"
echo ""
echo "=== OVERVIEW ==="
echo "  PineLabs provides physical POS terminals for card/UPI payments."
echo "  Integration allows SuperMandi POS app to initiate payments"
echo "  on the PineLabs terminal and receive transaction callbacks."
echo ""
echo "=== SDK INSTALLATION ==="
echo ""
echo "  1. Contact PineLabs for merchant onboarding"
echo "  2. Obtain PineLabs SDK for Android:"
echo "     - Download from PineLabs developer portal"
echo "     - Add to android/app/libs/ directory"
echo "  3. Add dependency in android/app/build.gradle:"
echo "     implementation files('libs/pinelabs-sdk.aar')"
echo "  4. React Native bridge:"
echo "     - Create NativeModule: PineLabsBridge.java"
echo "     - Expose methods: initPayment, checkStatus, cancelPayment"
echo ""
echo "=== DEVICE PAIRING ==="
echo ""
echo "  PineLabs terminal connects to POS app via:"
echo "    1. Bluetooth: Terminal and phone on same Bluetooth pair"
echo "    2. Wi-Fi: Terminal and phone on same network"
echo "    3. Cloud: Via PineLabs cloud relay (recommended)"
echo ""
echo "  Configuration:"
echo "    - Terminal serial number stored in store config"
echo "    - Pairing done once during store setup"
echo "    - Backend stores terminal mapping: store_id → terminal_serial"
echo ""
echo "=== PAYMENT INITIATION VIA INTENT ==="
echo ""
echo "  Android Intent-based payment flow:"
echo ""
echo "  1. POS app creates payment intent:"
echo "     const intent = {"
echo "       action: 'com.pinelabs.masterapp.SERVER',"
echo "       extras: {"
echo "         TransactionType: 4001,  // SALE"
echo "         BillingAmount: 15000,   // Amount in paise (150.00 INR)"
echo "         MerchantId: 'MERCHANT_ID',"
echo "         SecurityToken: 'TOKEN',"
echo "         OrderId: 'ORD-12345'"
echo "       }"
echo "     };"
echo ""
echo "  2. Launch PineLabs app:"
echo "     startActivityForResult(intent, PINELABS_REQUEST_CODE);"
echo ""
echo "  3. PineLabs app handles card tap/insert/swipe"
echo "  4. Result returned to SuperMandi POS via onActivityResult"
echo ""
echo "=== TRANSACTION CALLBACK HANDLING ==="
echo ""
echo "  onActivityResult returns:"
echo "    - ResponseCode: 0 = success, others = failure"
echo "    - ApprovalCode: Bank authorization code"
echo "    - RRN: Retrieval Reference Number"
echo "    - CardType: VISA/MC/RUPAY/UPI"
echo "    - CardLastFourDigits: For receipt printing"
echo ""
echo "  POS app handling:"
echo "    if (responseCode === 0) {"
echo "      // Payment successful"
echo "      // 1. Save transaction details to backend"
echo "      // 2. Update order status to PAID"
echo "      // 3. Print receipt with card details"
echo "    } else {"
echo "      // Payment failed — show error, allow retry"
echo "    }"
echo ""
echo "=== SETTLEMENT RECONCILIATION ==="
echo ""
echo "  Daily settlement process:"
echo "    1. PineLabs batches transactions end-of-day"
echo "    2. Settlement report available via PineLabs merchant portal"
echo "    3. Backend reconciliation job:"
echo "       - Fetch PineLabs settlement CSV/API"
echo "       - Match against orders.sales payment records"
echo "       - Flag mismatches for manual review"
echo "    4. Settlement typically T+1 (next business day)"
echo ""
echo "  Reconciliation endpoint:"
echo "    POST /api/v1/payments/pinelabs/reconcile"
echo "    Body: { settlementDate, terminalSerial }"
echo ""
echo "=== VOID / REFUND ==="
echo ""
echo "  Same-day void:"
echo "    TransactionType: 4002 (VOID)"
echo "    OriginalTransactionId: from original sale"
echo ""
echo "  Refund (after settlement):"
echo "    TransactionType: 4003 (REFUND)"
echo "    OriginalRRN: from original sale"
echo "    RefundAmount: full or partial"
echo ""
echo "=== IMPLEMENTATION CHECKLIST ==="
echo "  [ ] PineLabs merchant onboarding complete"
echo "  [ ] SDK integrated in Android build"
echo "  [ ] React Native bridge module created"
echo "  [ ] Terminal pairing flow in store setup"
echo "  [ ] Payment initiation via intent"
echo "  [ ] Callback handling and order update"
echo "  [ ] Receipt printing with card details"
echo "  [ ] Void and refund flows"
echo "  [ ] Settlement reconciliation job"
echo "  [ ] End-to-end testing with test terminal"
echo ""
echo "Done."
