#!/bin/bash
# GCP-STG-0699: Multi-store — store-level feature flag overrides
set -euo pipefail
echo "=== MULTI-STORE: FEATURE FLAGS ==="
echo ""
echo "CONCEPT: Enable/disable features per store (not globally)"
echo ""
echo "USE CASES:"
echo "  - Beta test voice search on 10 pilot stores before rollout"
echo "  - Enable BNPL for credit-approved stores only"
echo "  - Disable UPI for stores without bank verification"
echo "  - Enable weighing scale integration for stores with hardware"
echo ""
echo "DATA MODEL:"
echo "  New table: platform.store_feature_flags"
echo "  (store_id UUID, feature_key TEXT, enabled BOOLEAN, metadata JSONB)"
echo "  PRIMARY KEY (store_id, feature_key)"
echo ""
echo "API:"
echo "  GET  /pos/store/features → { voice_search: true, bnpl: false, ... }"
echo "  PUT  /admin/stores/:id/features → SuperAdmin sets flags"
echo ""
echo "FRONTEND:"
echo "  POS app fetches flags on login, caches in settingsStore"
echo "  Conditional rendering: if (features.voice_search) show mic button"
echo ""
echo "CURRENT STATE:"
echo "  FEATURE_REORDER_ENABLED is a global env var (all stores)"
echo "  voiceEnabled is per-device (settingsStore)"
echo "  Need: per-store server-side flags"
echo ""
echo "MIGRATION: CREATE TABLE platform.store_feature_flags (...)"
echo "=== FEATURE DESIGN COMPLETE ==="
