#!/bin/bash
# GCP-STG-0630: Secret rotation schedule documentation
echo "=== SECRET ROTATION SCHEDULE ==="
echo ""
echo "| Secret | Rotation Period | Procedure | Last Rotated |"
echo "|--------|----------------|-----------|--------------|"
echo "| JWT_SECRET | 90 days | deploy.yml dual-secret (GCP-STG-0480) | TBD |"
echo "| JWT_SECRET_PREVIOUS | Set during rotation | Copy old JWT_SECRET here | TBD |"
echo "| DATABASE_URL | On credential change | Update Secret Manager | TBD |"
echo "| DB_PASSWORD | 90 days | Cloud SQL → Reset password | TBD |"
echo "| SMTP_PASS | On provider rotation | Gmail App Password | TBD |"
echo "| WHATSAPP_ACCESS_TOKEN | 60 days (Meta policy) | Meta Business Suite | TBD |"
echo "| WHATSAPP_APP_SECRET | On regeneration | Meta Developer Console | TBD |"
echo "| OPENAI_API_KEY | 90 days | OpenAI Dashboard | TBD |"
echo "| RAZORPAY_WEBHOOK_SECRET | On regeneration | Razorpay Dashboard | TBD |"
echo "| INVOICE_SIGNING_KEY | 180 days | Generate new HMAC key | TBD |"
echo "| SERVICE_TOKEN_SECRET | 90 days | Internal service auth | TBD |"
echo "| ADMIN_TOKEN | On compromise only | Regenerate + redeploy | TBD |"
echo ""
echo "Rotation procedure:"
echo "  1. Generate new secret value"
echo "  2. gcloud secrets versions add SECRET_NAME --data-file=- <<< 'new_value'"
echo "  3. For JWT: copy old to JWT_SECRET_PREVIOUS first"
echo "  4. Deploy (Cloud Run auto-picks latest secret version)"
echo "  5. Verify service health after deploy"
echo "  6. After 24h: remove JWT_SECRET_PREVIOUS if set"
echo "=== SCHEDULE COMPLETE ==="
