-- Migration: 100_pos_device_activation_codes
-- POS-DEV-001/RET-WEB-002: Device-generated activation codes for binding
-- Creates table for storing short-lived activation codes generated by POS devices
-- Safe to run multiple times (idempotent)

BEGIN;

-- =============================================================================
-- Step 1: Create device_activation_codes table
-- =============================================================================

CREATE TABLE IF NOT EXISTS pos.device_activation_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Activation code (format: SM-XXXX-XX)
  code VARCHAR(12) UNIQUE NOT NULL,

  -- Device that generated this code
  device_fingerprint VARCHAR(255) NOT NULL,

  -- Time-limited validity
  expires_at TIMESTAMPTZ NOT NULL,

  -- Used tracking
  used_at TIMESTAMPTZ,

  -- Binding result (filled when code is used)
  bound_store_id UUID REFERENCES platform.stores(id),
  bound_device_id UUID,  -- References pos.pos_devices after device is created

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Created pos.device_activation_codes table

-- =============================================================================
-- Step 2: Add indexes for efficient lookup
-- =============================================================================

-- Primary lookup: by code
CREATE INDEX IF NOT EXISTS idx_device_activation_codes_code
ON pos.device_activation_codes(code);

-- Fingerprint lookup: to invalidate old codes for same device
CREATE INDEX IF NOT EXISTS idx_device_activation_codes_fingerprint
ON pos.device_activation_codes(device_fingerprint);

-- Expiry lookup: for cleanup of old unused codes
CREATE INDEX IF NOT EXISTS idx_device_activation_codes_expires
ON pos.device_activation_codes(expires_at)
WHERE used_at IS NULL;

-- Created indexes

-- =============================================================================
-- Step 3: Add documentation comments
-- =============================================================================

COMMENT ON TABLE pos.device_activation_codes IS 'Short-lived activation codes generated by POS devices for binding (POS-DEV-001/RET-WEB-002)';
COMMENT ON COLUMN pos.device_activation_codes.code IS 'Activation code in SM-XXXX-XX format';
COMMENT ON COLUMN pos.device_activation_codes.device_fingerprint IS 'Fingerprint of the POS device that generated this code';
COMMENT ON COLUMN pos.device_activation_codes.expires_at IS 'Code expiry time (typically 15 minutes after creation)';
COMMENT ON COLUMN pos.device_activation_codes.used_at IS 'When the code was used to bind a device (NULL if unused)';
COMMENT ON COLUMN pos.device_activation_codes.bound_store_id IS 'Store that the device was bound to (set on successful activation)';
COMMENT ON COLUMN pos.device_activation_codes.bound_device_id IS 'Device record created on successful activation';

COMMIT;
