/**
 * V3-FIX-145: Dual invoice chain for principal procurement
 *
 * For every completed catalogue procurement transaction:
 * 1. Supplier invoice: supplier → SuperMandi (uploaded by supplier)
 * 2. Retailer invoice: SuperMandi → retailer (generated by system)
 *
 * Both invoices are:
 * - Linked to the same procurement order pair
 * - Immutable once generated (append-only corrections via credit notes)
 * - Stored with versioned references
 * - Available for download from POS, retailer web, supplier portal
 * - Dispatchable via WhatsApp with delivery logging
 */

export type InvoiceType = "SUPPLIER_TO_SUPERMANDI" | "SUPERMANDI_TO_RETAILER";

export type InvoiceStatus = "draft" | "generated" | "dispatched" | "acknowledged";

export interface DualInvoicePair {
  /** The linked order pair this invoice set belongs to */
  retailerOrderId: string;
  supplierProcurementId: string;

  /** Supplier → SuperMandi invoice */
  supplierInvoice: {
    invoiceId: string | null;
    type: "SUPPLIER_TO_SUPERMANDI";
    status: InvoiceStatus;
    uploadedBy: "supplier";
    fileRef: string | null;
    generatedAt: string | null;
  };

  /** SuperMandi → Retailer invoice */
  retailerInvoice: {
    invoiceId: string | null;
    type: "SUPERMANDI_TO_RETAILER";
    status: InvoiceStatus;
    generatedBy: "system";
    fileRef: string | null;
    generatedAt: string | null;
  };
}

/**
 * Validate that a dual invoice pair is complete for a given order.
 */
export function validateInvoicePairCompleteness(pair: DualInvoicePair): {
  complete: boolean;
  missing: string[];
} {
  const missing: string[] = [];

  if (!pair.supplierInvoice.invoiceId) {
    missing.push("Supplier invoice not uploaded");
  }
  if (!pair.retailerInvoice.invoiceId) {
    missing.push("Retailer invoice not generated");
  }
  if (pair.supplierInvoice.status === "draft") {
    missing.push("Supplier invoice still in draft");
  }
  if (pair.retailerInvoice.status === "draft") {
    missing.push("Retailer invoice still in draft");
  }

  return { complete: missing.length === 0, missing };
}

/**
 * V3-FIX-145: WhatsApp dispatch logging for invoice delivery.
 */
export interface InvoiceDispatchLog {
  invoiceId: string;
  invoiceType: InvoiceType;
  recipientPhone: string;
  recipientRole: "supplier" | "retailer" | "admin";
  dispatchedAt: string;
  status: "sent" | "failed" | "pending_retry";
  retryCount: number;
  lastError: string | null;
}
