const fs = require('fs');
const path = require('path');

const {
  withDangerousMod,
  createRunOncePlugin,
} = require('@expo/config-plugins');

function toGradlePath(p) {
  // Gradle on Windows accepts forward slashes reliably.
  return p.replace(/\\/g, '/');
}

function resolveAndroidSdkDir() {
  // Prefer ANDROID_HOME if user has it set.
  if (process.env.ANDROID_HOME && process.env.ANDROID_HOME.trim()) {
    return process.env.ANDROID_HOME.trim();
  }

  // Default Android Studio SDK location on Windows.
  if (process.env.LOCALAPPDATA && process.env.LOCALAPPDATA.trim()) {
    return path.join(process.env.LOCALAPPDATA.trim(), 'Android', 'Sdk');
  }

  return null;
}

function withAndroidLocalProperties(config) {
  return withDangerousMod(config, [
    'android',
    async (config) => {
      const sdkDir = resolveAndroidSdkDir();
      if (!sdkDir) {
        console.warn(
          '[withAndroidLocalProperties] Could not resolve Android SDK directory. Set ANDROID_HOME to fix.'
        );
        return config;
      }

      const androidRoot = config.modRequest.platformProjectRoot;
      const localPropsPath = path.join(androidRoot, 'local.properties');

      // Create/overwrite `android/local.properties` every prebuild so `npx expo run:android`
      // works even after `npx expo prebuild --clean`.
      const contents =
        '## Auto-generated by plugins/withAndroidLocalProperties.js\n' +
        '## Do not commit secrets. This file is safe to regenerate.\n' +
        `sdk.dir=${toGradlePath(sdkDir)}\n`;

      fs.writeFileSync(localPropsPath, contents, 'utf8');
      return config;
    },
  ]);
}

module.exports = createRunOncePlugin(
  withAndroidLocalProperties,
  'withAndroidLocalProperties',
  '1.0.0'
);

