#!/bin/bash
# GCP-STG-0607: Verify Cloud SQL connections vs pool config
echo "=== DB CONNECTION CHECK ==="
echo "Cloud Run config:"
echo "  max-instances: 10"
echo "  DB_POOL_MAX: 10 (per instance)"
echo "  Total max connections: 100"
echo ""
echo "Cloud SQL tier check:"
echo "  db-f1-micro: max_connections = 25 (TOO LOW)"
echo "  db-g1-small: max_connections = 200 (OK)"
echo "  db-custom-1-3840: max_connections = 100 (TIGHT)"
echo ""
echo "Verify with:"
echo "  gcloud sql instances describe supermandi-staging --format='value(settings.tier)'"
echo "  psql -c 'SHOW max_connections;'"
echo ""
echo "If max_connections < 120, either:"
echo "  1. Reduce DB_POOL_MAX to 5 (total 50)"
echo "  2. Upgrade Cloud SQL tier"
echo "  3. Reduce max-instances to 5"
echo "=== CHECK COMPLETE ==="
