#!/bin/bash
# GCP-STG-0678: Request latency alerting for Cloud Run
echo "=== LATENCY ALERT SETUP ==="
echo "Create in Cloud Console -> Monitoring -> Alerting:"
echo ""
echo "Alert 1: P95 latency > 2s"
echo "  Resource: Cloud Run Revision"
echo "  Metric: run.googleapis.com/request_latencies"
echo "  Aggregation: 95th percentile"
echo "  Threshold: > 2000ms for 5 minutes"
echo ""
echo "Alert 2: P99 latency > 5s"
echo "  Metric: run.googleapis.com/request_latencies"
echo "  Aggregation: 99th percentile"
echo "  Threshold: > 5000ms for 5 minutes"
echo ""
echo "Alert 3: Request count spike"
echo "  Metric: run.googleapis.com/request_count"
echo "  Threshold: > 1000 req/min (200% of baseline)"
echo "=== SETUP COMPLETE ==="
