#!/bin/bash
# GCP-STG-0639: Redis (Memorystore) alerting — memory > 80%
echo "=== REDIS ALERT SETUP ==="
echo "Create in Cloud Console → Monitoring → Alerting:"
echo ""
echo "Alert 1: Redis Memory > 80%"
echo "  Resource: Memorystore for Redis"
echo "  Metric: redis.googleapis.com/stats/memory/usage_ratio"
echo "  Threshold: > 0.8 for 5 minutes"
echo "  Notification: email + Slack"
echo ""
echo "Alert 2: Redis Connected Clients > 100"
echo "  Metric: redis.googleapis.com/clients/connected"
echo "  Threshold: > 100 for 5 minutes"
echo ""
echo "Current Redis config:"
echo "  Host: 10.107.71.27 (Memorystore private IP)"
echo "  Port: 6379"
echo "  Used for: rate limiting, caching, session blacklist"
echo ""
echo "If memory > 80%, consider:"
echo "  1. Reduce TTL on rate limit keys"
echo "  2. Clear unused cache entries"
echo "  3. Upgrade Memorystore tier"
echo "=== SETUP COMPLETE ==="
