#!/bin/bash
# GCP-STG-0683: PostgreSQL vacuum/analyze schedule
#
# Documents Cloud SQL autovacuum settings and manual maintenance
# for large tables. Cloud SQL has autovacuum enabled by default,
# but large tables may benefit from scheduled manual VACUUM ANALYZE.
#
# Usage:
#   bash scripts/gcp/postgres-maintenance.sh

set -euo pipefail

echo "=== POSTGRESQL VACUUM/ANALYZE SCHEDULE ==="
echo ""
echo "AUTOVACUUM (Cloud SQL Default — Enabled)"
echo "  Cloud SQL for PostgreSQL has autovacuum ON by default."
echo "  Default settings (tunable via database flags):"
echo "    autovacuum = on"
echo "    autovacuum_vacuum_threshold = 50"
echo "    autovacuum_analyze_threshold = 50"
echo "    autovacuum_vacuum_scale_factor = 0.2"
echo "    autovacuum_analyze_scale_factor = 0.1"
echo "    autovacuum_naptime = 60s"
echo ""
echo "  To check current settings:"
echo "    SHOW autovacuum;"
echo "    SELECT name, setting FROM pg_settings WHERE name LIKE 'autovacuum%';"
echo ""
echo "LARGE TABLES REQUIRING EXTRA ATTENTION"
echo "  These tables grow fastest and may need manual VACUUM ANALYZE:"
echo ""
echo "  1. orders.sales"
echo "     - Every checkout creates rows; highest write volume"
echo "     - Schedule: Weekly VACUUM ANALYZE"
echo "     - Command: VACUUM (VERBOSE, ANALYZE) orders.sales;"
echo ""
echo "  2. inventory.inventory_ledger"
echo "     - Stock movements on every sale, stock-in, adjustment"
echo "     - Schedule: Weekly VACUUM ANALYZE"
echo "     - Command: VACUUM (VERBOSE, ANALYZE) inventory.inventory_ledger;"
echo ""
echo "  3. catalog.store_products"
echo "     - Frequent price/stock updates per store"
echo "     - Schedule: Weekly VACUUM ANALYZE"
echo "     - Command: VACUUM (VERBOSE, ANALYZE) catalog.store_products;"
echo ""
echo "MANUAL MAINTENANCE COMMANDS"
echo "  Run via Cloud SQL proxy or Cloud Console SQL editor:"
echo ""
echo "  -- Full vacuum (reclaims space, updates stats)"
echo "  VACUUM (VERBOSE, ANALYZE) orders.sales;"
echo "  VACUUM (VERBOSE, ANALYZE) inventory.inventory_ledger;"
echo "  VACUUM (VERBOSE, ANALYZE) catalog.store_products;"
echo ""
echo "  -- Check last vacuum/analyze times"
echo "  SELECT schemaname, relname, last_vacuum, last_autovacuum,"
echo "         last_analyze, last_autoanalyze, n_dead_tup"
echo "  FROM pg_stat_user_tables"
echo "  WHERE n_dead_tup > 1000"
echo "  ORDER BY n_dead_tup DESC;"
echo ""
echo "  -- Check table bloat"
echo "  SELECT schemaname, tablename,"
echo "         pg_size_pretty(pg_total_relation_size(schemaname||'.'||tablename)) as total_size"
echo "  FROM pg_tables"
echo "  WHERE schemaname NOT IN ('pg_catalog','information_schema')"
echo "  ORDER BY pg_total_relation_size(schemaname||'.'||tablename) DESC"
echo "  LIMIT 10;"
echo ""
echo "SCHEDULED MAINTENANCE WINDOW"
echo "  Cloud SQL maintenance window (for Cloud SQL-initiated patches/updates):"
echo "    gcloud sql instances patch supermandi-staging \\"
echo "      --maintenance-window-day=SUN \\"
echo "      --maintenance-window-hour=3 \\"
echo "      --maintenance-release-channel=production"
echo ""
echo "  This sets Cloud SQL auto-maintenance to Sunday 3 AM IST."
echo "  For manual VACUUM, schedule a Cloud Scheduler job or"
echo "  GitHub Actions cron that connects via Cloud SQL proxy."
echo ""
echo "TUNING AUTOVACUUM FOR HIGH-WRITE TABLES"
echo "  If autovacuum cannot keep up, tune per-table:"
echo "    ALTER TABLE orders.sales SET (autovacuum_vacuum_scale_factor = 0.05);"
echo "    ALTER TABLE orders.sales SET (autovacuum_analyze_scale_factor = 0.02);"
echo "    ALTER TABLE inventory.inventory_ledger SET (autovacuum_vacuum_scale_factor = 0.05);"
echo ""
echo "Done."
