#!/bin/bash
# GCP-STG-0686: CDN configuration for product images from GCS
echo "=== CDN FOR PRODUCT IMAGES ==="
echo ""
echo "Option A: Cloud CDN with GCS backend (recommended)"
echo "  1. Create backend bucket:"
echo "     gcloud compute backend-buckets create supermandi-images-cdn \\"
echo "       --gcs-bucket-name=supermandi-pos-images \\"
echo "       --enable-cdn \\"
echo "       --cache-mode=CACHE_ALL_STATIC \\"
echo "       --default-ttl=86400"
echo ""
echo "  2. Add URL map path rule:"
echo "     /images/* → supermandi-images-cdn backend bucket"
echo ""
echo "  3. Configure CORS on GCS bucket:"
echo "     gsutil cors set cors.json gs://supermandi-pos-images"
echo ""
echo "Option B: Signed URLs (no CDN, direct GCS)"
echo "  Already implemented in imageService.ts"
echo "  Pros: No CDN cost, fine-grained access control"
echo "  Cons: Higher latency, no edge caching"
echo ""
echo "For launch: Use Option B (signed URLs already working)"
echo "Post-launch: Migrate to Option A when image volume justifies CDN cost"
echo "=== SETUP COMPLETE ==="
