#!/bin/bash
# GCP-STG-0612: Verify Firebase App Check with reCAPTCHA
echo "=== FIREBASE APP CHECK ==="
echo "App Check prevents unauthorized clients from calling Firebase APIs."
echo ""
echo "Setup steps:"
echo "  1. Firebase Console → App Check → Register apps"
echo "  2. Provider: reCAPTCHA Enterprise"
echo "  3. Get site key → set in env vars:"
echo "     VITE_FIREBASE_RECAPTCHA_SITE_KEY (retailer-admin)"
echo "     NEXT_PUBLIC_FIREBASE_RECAPTCHA_SITE_KEY (supplier-portal)"
echo ""
echo "  4. Frontend initialization:"
echo "     import { initializeAppCheck, ReCaptchaEnterpriseProvider } from 'firebase/app-check';"
echo "     initializeAppCheck(app, { provider: new ReCaptchaEnterpriseProvider(siteKey) });"
echo ""
echo "  5. Enforce in Firebase Console → App Check → APIs → Enforce"
echo ""
echo "Verify:"
echo "  firebase appcheck:list --project supermandi-pos"
echo ""
echo "Without App Check, anyone can use the Firebase config (public in JS)"
echo "to call signInWithPhoneNumber and consume OTP quota."
echo "=== CHECK COMPLETE ==="
