#!/bin/bash
# GCP-STG-0611: Verify Firebase billing plan for Phone Auth at scale
echo "=== FIREBASE BILLING CHECK ==="
echo "Firebase Spark (free) plan: 10,000 phone verifications/month"
echo "Firebase Blaze (pay-as-you-go): unlimited, ~\$0.06/verification (India)"
echo ""
echo "At 10K users × 1 login/day = 300K verifications/month"
echo "Cost estimate: ~\$18K/month on Blaze"
echo ""
echo "Verify plan:"
echo "  Firebase Console → ⚙️ Project settings → Usage and billing"
echo "  OR: gcloud billing projects describe supermandi-pos"
echo ""
echo "SuperMandi architecture mitigates cost:"
echo "  - POS: Custom WhatsApp OTP (FREE, no Firebase)"
echo "  - Web portals: Firebase Phone Auth (costs apply)"
echo "  - Session persistence: Reduces re-auth frequency"
echo ""
echo "ACTION: Upgrade to Blaze if still on Spark before 10K users"
echo "=== CHECK COMPLETE ==="
