#!/bin/bash
# GCP-STG-0610: Verify Firebase authorized domains
echo "=== FIREBASE AUTHORIZED DOMAINS CHECK ==="
echo "Firebase Console → Authentication → Settings → Authorized domains"
echo ""
echo "Required domains for staging:"
echo "  ✅ localhost (development)"
echo "  ✅ staging.supermandi.tech"
echo "  ✅ www.staging.supermandi.tech"
echo ""
echo "Required domains for production:"
echo "  ✅ app.supermandi.tech (retailer portal)"
echo "  ✅ supplier.supermandi.tech (supplier portal)"
echo "  ✅ admin.supermandi.tech (superadmin)"
echo "  ✅ supermandi.tech (landing)"
echo ""
echo "Verify with Firebase CLI:"
echo "  firebase auth:export-authorized-domains --project supermandi-pos"
echo ""
echo "If domains missing: Firebase Console → Auth → Settings → Add domain"
echo "Without these, Firebase phone OTP will fail with auth/unauthorized-domain"
echo "=== CHECK COMPLETE ==="
