#!/bin/bash
# GCP-STG-0608: Verify uptime-probe alerting
echo "=== UPTIME PROBE ALERT CHECK ==="
echo ""
echo "Probe runs every 5 minutes (cron: */5 * * * *)"
echo "File: .github/workflows/uptime-probe.yml"
echo ""
echo "Current behavior on failure:"
echo "  - GitHub Actions shows FAIL in workflow history"
echo "  - GitHub can send email notification on workflow failure"
echo "  - Creates GitHub issue with label 'uptime-alert' + 'critical'"
echo "  - Auto-closes alert issues when all portals recover"
echo ""
echo "To enable email alerts:"
echo "  GitHub -> Settings -> Notifications -> Actions"
echo "  Enable: 'Send notifications for failed workflows only'"
echo ""
echo "To add Slack alerting:"
echo "  Add step after URL checks:"
echo "    - name: Alert Slack"
echo "      if: failure()"
echo "      uses: 8398a7/action-slack@v3"
echo "      with:"
echo "        status: failure"
echo "        webhook_url: \${{ secrets.SLACK_WEBHOOK }}"
echo ""
echo "Verify probe is running:"
echo "  gh run list --workflow=uptime-probe.yml --limit=5"
echo "=== CHECK COMPLETE ==="
