#!/bin/bash
# GCP-STG-0684: Backup restore test plan
#
# Documents the procedure to test Cloud SQL backup restoration.
# Run this quarterly to verify backups are valid and restorable.
#
# Usage:
#   bash scripts/tests/backup-restore-test.sh

set -euo pipefail

PROJECT_ID="${GCP_PROJECT_ID:-supermandi-backend}"
SOURCE_INSTANCE="supermandi-staging"
TEST_INSTANCE="supermandi-restore-test"
REGION="asia-south1"

echo "=== BACKUP RESTORE TEST PLAN ==="
echo ""
echo "PURPOSE: Verify Cloud SQL backups can be restored and data is intact."
echo "FREQUENCY: Quarterly (or after major migration batches)"
echo ""
echo "=== STEP 1: List Available Backups ==="
echo "  gcloud sql backups list --instance=$SOURCE_INSTANCE --project=$PROJECT_ID"
echo ""
echo "  Note the BACKUP_ID of the latest successful backup."
echo "  Backups are retained for 7 days by default (configurable)."
echo ""
echo "=== STEP 2: Create Test Instance ==="
echo "  gcloud sql instances create $TEST_INSTANCE \\"
echo "    --project=$PROJECT_ID \\"
echo "    --region=$REGION \\"
echo "    --database-version=POSTGRES_15 \\"
echo "    --tier=db-f1-micro \\"
echo "    --no-assign-ip"
echo ""
echo "  Use db-f1-micro (smallest tier) to minimize cost."
echo "  Test instance is temporary — delete after verification."
echo ""
echo "=== STEP 3: Restore Backup to Test Instance ==="
echo "  gcloud sql backups restore BACKUP_ID \\"
echo "    --restore-instance=$TEST_INSTANCE \\"
echo "    --project=$PROJECT_ID"
echo ""
echo "  Wait for operation to complete (5-15 minutes depending on DB size)."
echo ""
echo "=== STEP 4: Run Migration Dry-Run ==="
echo "  Connect via Cloud SQL proxy to test instance:"
echo "    cloud-sql-proxy --gcloud-auth $PROJECT_ID:$REGION:$TEST_INSTANCE --port=15433"
echo ""
echo "  Run migration dry-run:"
echo "    DATABASE_URL=postgresql://postgres:PASSWORD@localhost:15433/supermandi \\"
echo "      node backend/scripts/migrate-prod.js dry-run"
echo ""
echo "  Expected: All migrations already applied (0 pending)."
echo "  If pending migrations exist, investigate why backup is behind."
echo ""
echo "=== STEP 5: Verify Row Counts ==="
echo "  Connect to test instance and compare row counts against source:"
echo ""
echo "  SELECT 'auth.users' as tbl, count(*) FROM auth.users"
echo "  UNION ALL"
echo "  SELECT 'catalog.store_products', count(*) FROM catalog.store_products"
echo "  UNION ALL"
echo "  SELECT 'orders.sales', count(*) FROM orders.sales"
echo "  UNION ALL"
echo "  SELECT 'inventory.inventory_ledger', count(*) FROM inventory.inventory_ledger"
echo "  UNION ALL"
echo "  SELECT 'platform.stores', count(*) FROM platform.stores;"
echo ""
echo "  Compare counts with source instance. Counts should match"
echo "  (within the backup window delta)."
echo ""
echo "=== STEP 6: Compare Schema ==="
echo "  Dump schema from both instances and diff:"
echo ""
echo "  pg_dump --schema-only -h localhost -p 15432 supermandi > /tmp/source-schema.sql"
echo "  pg_dump --schema-only -h localhost -p 15433 supermandi > /tmp/restored-schema.sql"
echo "  diff /tmp/source-schema.sql /tmp/restored-schema.sql"
echo ""
echo "  Expected: No differences (or only sequence values differ)."
echo ""
echo "=== STEP 7: Delete Test Instance ==="
echo "  gcloud sql instances delete $TEST_INSTANCE \\"
echo "    --project=$PROJECT_ID \\"
echo "    --quiet"
echo ""
echo "  IMPORTANT: Always delete the test instance after verification"
echo "  to avoid ongoing charges."
echo ""
echo "=== PASS CRITERIA ==="
echo "  1. Backup restores without errors"
echo "  2. Migration dry-run shows 0 pending migrations"
echo "  3. Row counts match source (within backup window)"
echo "  4. Schema diff shows no structural differences"
echo "  5. Test instance deleted after verification"
echo ""
echo "Done."
