#!/bin/bash
# GCP-STG-0694: Chaos test — Cloud SQL connection spike
set -euo pipefail
echo "=== CHAOS TEST: DB CONNECTION SPIKE ==="
echo ""
echo "PURPOSE: Verify pool exhaustion handling when DB connections maxed out"
echo ""
echo "TEST STEPS:"
echo "  1. Current config: DB_POOL_MAX=10, max-instances=10 → 100 max connections"
echo "  2. Cloud SQL db-g1-small: max_connections=200 (OK headroom)"
echo "  3. Simulate spike: Run 200 concurrent slow queries"
echo "     curl -s 'https://staging.supermandi.tech/api/v1/admin/analytics/slow-movers?limit=10000' &"
echo "     (repeat 200 times)"
echo "  4. Monitor:"
echo "     a. Pool wait time in logs ('pool exhausted' or 'connection timeout')"
echo "     b. API responses: should return 503 'Database busy' not hang forever"
echo "     c. Cloud SQL connections: gcloud sql instances describe --format metrics"
echo "  5. Stop traffic, verify recovery"
echo ""
echo "PASS CRITERIA:"
echo "  ✅ No hanging requests (all timeout within 30s)"
echo "  ✅ Pool exhaustion returns 503 (not crash)"
echo "  ✅ Normal requests resume after spike ends"
echo "  ✅ No connection leaks (pool returns to baseline)"
echo ""
echo "CURRENT PROTECTION:"
echo "  - pg pool max: 10 per instance"
echo "  - Connection timeout: 30s (pool.query timeout)"
echo "  - Cloud Run concurrency: 100 (limits parallel requests)"
echo "=== TEST PLAN COMPLETE ==="
