#!/bin/bash
# GCP-STG-0693: Chaos test — Redis down, verify rate limiting degrades
set -euo pipefail
echo "=== CHAOS TEST: REDIS DOWN ==="
echo ""
echo "PURPOSE: Verify backend degrades gracefully when Memorystore is unavailable"
echo ""
echo "TEST STEPS:"
echo "  1. Stop Redis: gcloud redis instances update supermandi-redis --region=asia-south1 --no-enable-apis"
echo "     (Or simulate: set REDIS_URL to invalid host)"
echo "  2. Verify backend behavior:"
echo "     a. API requests still work (rate limiting skipped, not crashed)"
echo "     b. Login/OTP endpoints functional (OTP stored in DB, not Redis)"
echo "     c. Token blacklist unavailable (logged out tokens stay valid until expiry)"
echo "     d. Cache misses handled (queries go directly to DB)"
echo "     e. Health endpoint returns 200 (Redis is non-critical)"
echo "  3. Restore Redis"
echo "  4. Verify: Rate limiting resumes, cache rebuilds"
echo ""
echo "PASS CRITERIA:"
echo "  ✅ Zero 5xx errors from Redis unavailability"
echo "  ✅ All API endpoints return valid responses"
echo "  ✅ Rate limiting gracefully skipped (not enforced = permissive)"
echo "  ✅ Recovery automatic on Redis restore"
echo ""
echo "RISK: Without rate limiting, endpoints are briefly unprotected"
echo "MITIGATION: Cloud Run concurrency limit (100) acts as natural throttle"
echo "=== TEST PLAN COMPLETE ==="
