#!/bin/bash
# GCP-STG-0692: Chaos test — kill main-backend, verify POS graceful error
set -euo pipefail
echo "=== CHAOS TEST: KILL MAIN-BACKEND ==="
echo ""
echo "PURPOSE: Verify POS app shows graceful error when backend is down"
echo ""
echo "TEST STEPS:"
echo "  1. POS app open on SELL screen with products loaded"
echo "  2. Kill backend: gcloud run services update-traffic main-backend --to-revisions=LATEST=0 --region=asia-south1"
echo "  3. On POS app:"
echo "     a. Search product → should show 'Server unavailable' toast (not crash)"
echo "     b. Create cash sale → should succeed (offline mode)"
echo "     c. Create UPI sale → should show 'Payment requires internet' error"
echo "     d. Sync button → should show 'Sync failed — will retry' message"
echo "     e. Navigate all tabs → no crashes"
echo "  4. Restore: gcloud run services update-traffic main-backend --to-revisions=LATEST=100 --region=asia-south1"
echo "  5. Verify: Offline sales sync automatically within 60 seconds"
echo ""
echo "PASS CRITERIA:"
echo "  ✅ No crashes or white screens"
echo "  ✅ Clear error messages (not HTTP codes)"
echo "  ✅ Offline cash sales work"
echo "  ✅ UPI correctly blocked"
echo "  ✅ Auto-recovery on backend restore"
echo ""
echo "AUTOMATION: Manual — requires staging environment + POS device"
echo "=== TEST PLAN COMPLETE ==="
