#!/bin/bash
# GCP-STG-0695: Chaos test — GCS unavailable, verify invoice fails gracefully
set -euo pipefail
echo "=== CHAOS TEST: GCS UNAVAILABLE ==="
echo ""
echo "PURPOSE: Verify invoice/document upload fails gracefully when GCS is down"
echo ""
echo "TEST STEPS:"
echo "  1. Revoke Cloud Run SA access to GCS bucket:"
echo "     gsutil iam ch -d serviceAccount:cloudrun-backend@supermandi-backend.iam.gserviceaccount.com gs://supermandi-pos-documents"
echo "  2. Create a sale on POS → verify:"
echo "     a. Sale succeeds (GCS upload is async, non-blocking)"
echo "     b. Invoice PDF generation logged as failed"
echo "     c. No crash, no 500 on sale endpoint"
echo "     d. 'Invoice will be generated later' message (if applicable)"
echo "  3. Upload KYC document on supplier portal → verify:"
echo "     a. Upload shows clear error: 'Document upload failed'"
echo "     b. Registration can continue without document (saved as pending)"
echo "  4. Restore access:"
echo "     gsutil iam ch serviceAccount:cloudrun-backend@supermandi-backend.iam.gserviceaccount.com:objectAdmin gs://supermandi-pos-documents"
echo "  5. Verify: Pending documents/invoices retry and succeed"
echo ""
echo "PASS CRITERIA:"
echo "  ✅ Sales NOT blocked by GCS failure"
echo "  ✅ Clear error messages on document upload"
echo "  ✅ No data loss (sale records intact)"
echo "  ✅ Auto-recovery on GCS restore"
echo "=== TEST PLAN COMPLETE ==="
