#!/bin/bash
# GCP-STG-0690: Concurrent user test — 50 devices same store
echo "=== CONCURRENT USER TEST PLAN ==="
echo ""
echo "Simulates 50 POS devices making simultaneous sales in one store."
echo ""
echo "Load Test Command (uses existing stress-test.yml):"
echo "  gh workflow run stress-test.yml \\"
echo "    --ref main \\"
echo "    -f base_url=https://staging.supermandi.tech/api/v1 \\"
echo "    -f concurrent_users=50 \\"
echo "    -f duration=300"
echo ""
echo "Verification Queries (run after test):"
echo "  -- Total sales created (should be ~50 × requests)"
echo "  SELECT COUNT(*) FROM orders.sales WHERE store_id = 'test-store';"
echo ""
echo "  -- Stock consistency check (no negative stock)"
echo "  SELECT product_id, current_qty FROM inventory.stock_balances"
echo "  WHERE store_id = 'test-store' AND current_qty < 0;"
echo ""
echo "  -- Ledger reconciliation (SUM(delta) = stock_balances)"
echo "  SELECT sb.product_id, sb.current_qty, SUM(il.delta_qty) as ledger_sum"
echo "  FROM inventory.stock_balances sb"
echo "  JOIN inventory.inventory_ledger il ON sb.product_id = il.product_id AND sb.store_id = il.store_id"
echo "  WHERE sb.store_id = 'test-store'"
echo "  GROUP BY sb.product_id, sb.current_qty"
echo "  HAVING sb.current_qty != SUM(il.delta_qty);"
echo ""
echo "Pass Criteria:"
echo "  ✅ Zero stock inconsistencies"
echo "  ✅ Zero ledger divergence"
echo "  ✅ P95 latency < 500ms"
echo "  ✅ Zero 5xx errors"
echo "  ✅ No deadlocks in DB logs"
echo "=== TEST PLAN COMPLETE ==="
