#!/bin/bash
# GCP-STG-0689: Network partition test — POS offline 1 hour → reconnect → verify sync
echo "=== NETWORK PARTITION TEST PLAN ==="
echo ""
echo "Pre-conditions:"
echo "  1. POS app installed on test device (TG8HCYTGGQT885OF)"
echo "  2. Device enrolled to test store (SU260305-003)"
echo "  3. 10+ products synced to local storage"
echo ""
echo "Test Steps:"
echo "  1. BASELINE: Verify app shows online status, products loaded"
echo "  2. DISCONNECT: Enable airplane mode on device"
echo "  3. OFFLINE OPERATIONS (1 hour):"
echo "     - Create 3 cash sales (should succeed offline)"
echo "     - Search products (local search should work)"
echo "     - View stock (cached data should display)"
echo "     - Attempt UPI payment (should show 'Offline' error)"
echo "     - Navigate all screens (no crashes)"
echo "  4. RECONNECT: Disable airplane mode"
echo "  5. SYNC VERIFICATION:"
echo "     - App should auto-sync within 60 seconds"
echo "     - 3 offline sales should appear in backend"
echo "     - Stock should update to reflect sales"
echo "     - No duplicate sales or data corruption"
echo ""
echo "Pass Criteria:"
echo "  ✅ All offline sales synced correctly"
echo "  ✅ No data loss or duplication"
echo "  ✅ App did not crash during offline period"
echo "  ✅ UPI correctly blocked while offline"
echo "  ✅ Sync completed within 60 seconds"
echo ""
echo "Automation: Manual test — requires physical device"
echo "=== TEST PLAN COMPLETE ==="
