// STG-221: Replaced hardcoded hex colors with CSS variables for dark mode
// RET-WEB-002: Device Activation Page
// Allows retailers to activate POS devices using activation codes
// Activation code format: SM-XXXX-XX (generated by POS app)

import { useState, useCallback, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { useAuth } from '../lib/AuthContext';
import { authFetch, safeJson } from '../lib/api';
// T-112: Breadcrumb navigation
import Breadcrumb from '../components/Breadcrumb';
// UIUX-RET-002: Styled modal instead of window.confirm
import Modal from '../components/Modal';
import { logger } from '../lib/logger';

interface Device {
  id: string;
  fingerprint: string;
  label: string;
  deviceType: string;
  manufacturer?: string;
  model?: string;
  appVersion?: string;
  lastSeen?: string;
  createdAt: string;
  isActive: boolean;
}

// RET-AUD-027: Device deactivation response
interface DeviceUpdateResponse {
  success: boolean;
  device?: Device;
  error?: { code: string; message: string };
}

export default function DeviceActivationPage() {
  const { storeCode } = useParams<{ storeCode: string }>();
  const { accessToken, store } = useAuth();

  // Form state
  const [activationCode, setActivationCode] = useState('');
  const [devices, setDevices] = useState<Device[]>([]);
  const [loadingDevices, setLoadingDevices] = useState(false);
  const [devicesLoaded, setDevicesLoaded] = useState(false);

  // UI state
  const [activating, setActivating] = useState(false);
  const [deactivatingDeviceId, setDeactivatingDeviceId] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  // UIUX-RET-002: Styled confirmation modal for device toggle
  const [toggleConfirm, setToggleConfirm] = useState<{ deviceId: string; currentlyActive: boolean } | null>(null);

  // Format activation code as user types (SM-XXXX-XX)
  const formatActivationCode = useCallback((value: string): string => {
    // Remove all non-alphanumeric except hyphens
    const cleaned = value.toUpperCase().replace(/[^A-Z0-9-]/g, '');

    // If starts with SM-, keep it
    if (cleaned.startsWith('SM-')) {
      const rest = cleaned.substring(3).replace(/-/g, '');
      if (rest.length <= 4) {
        return `SM-${rest}`;
      } else if (rest.length <= 6) {
        return `SM-${rest.substring(0, 4)}-${rest.substring(4)}`;
      } else {
        return `SM-${rest.substring(0, 4)}-${rest.substring(4, 6)}`;
      }
    }

    // Auto-add SM- prefix if user types alphanumeric
    const alphaNum = cleaned.replace(/-/g, '');
    if (alphaNum.length === 0) return '';
    if (alphaNum.length <= 4) {
      return `SM-${alphaNum}`;
    } else if (alphaNum.length <= 6) {
      return `SM-${alphaNum.substring(0, 4)}-${alphaNum.substring(4)}`;
    } else {
      return `SM-${alphaNum.substring(0, 4)}-${alphaNum.substring(4, 6)}`;
    }
  }, []);

  // Handle code input change
  const handleCodeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const formatted = formatActivationCode(e.target.value);
    setActivationCode(formatted);
    setError(null);
    setSuccess(null);
  };

  // Validate activation code format
  const isValidCode = (code: string): boolean => {
    return /^SM-[A-Z0-9]{4}-[A-Z0-9]{2}$/.test(code);
  };

  // Load devices for this store
  // #184.19: Handle 401 and show error messages
  const loadDevices = useCallback(async () => {
    if (!accessToken) return;

    setLoadingDevices(true);
    setError(null);
    try {
      const response = await authFetch('/api/v1/retailer-admin/devices', accessToken);
      if (response.ok) {
        const data = await safeJson(response);
        setDevices(data.devices || []);
      } else if (response.status === 401) {
        setError('Session expired. Please log in again.');
      } else {
        const data = await safeJson(response);
        setError(data?.error?.message || `Failed to load devices (${response.status})`);
      }
    } catch (err) {
      logger.error('Failed to load devices:', err);
      setError(err instanceof Error && err.name === 'AbortError'
        ? 'Request timed out. Please try again.'
        : 'Network error loading devices. Please check your connection.');
    } finally {
      setLoadingDevices(false);
      setDevicesLoaded(true);
    }
  }, [accessToken]);

  // AUDIT-RET-030: Fix useState anti-pattern — use useEffect for side effects
  useEffect(() => {
    if (accessToken && !devicesLoaded) {
      loadDevices();
    }
  }, [accessToken, devicesLoaded]);

  // Handle activation
  const handleActivate = async () => {
    if (!accessToken || !isValidCode(activationCode)) return;

    setActivating(true);
    setError(null);
    setSuccess(null);

    try {
      const response = await authFetch('/api/v1/retailer-admin/devices/activate', accessToken, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ activation_code: activationCode }),
      });

      const data = await safeJson(response);

      if (response.ok && data.success) {
        setSuccess(`Device activated successfully! Device ID: ${data.device_id.substring(0, 8)}...`);
        setActivationCode('');
        // Reload devices list
        loadDevices();
      } else {
        // Handle specific error codes
        const errorCode = data.error?.code;
        switch (errorCode) {
          case 'CODE_NOT_FOUND':
            setError('Activation code not found. Please check the code and try again.');
            break;
          case 'CODE_ALREADY_USED':
            setError('This activation code has already been used.');
            break;
          case 'CODE_EXPIRED':
            setError('This activation code has expired. Please generate a new code on the POS device.');
            break;
          case 'VALIDATION_ERROR':
            setError(data.error?.message || 'Invalid activation code format.');
            break;
          default:
            setError(data.error?.message || 'Failed to activate device. Please try again.');
        }
      }
    } catch (err: any) {
      logger.error('Device activation error:', err);
      setError(err.message || 'Network error. Please check your connection.');
    } finally {
      setActivating(false);
    }
  };

  // RET-AUD-027: Handle device deactivation/reactivation
  // UIUX-RET-002: Show styled Modal instead of window.confirm
  const handleToggleDevice = async (deviceId: string, currentlyActive: boolean) => {
    if (!accessToken) return;

    setToggleConfirm({ deviceId, currentlyActive });
  };

  const confirmToggleDevice = async () => {
    if (!toggleConfirm || !accessToken) return;
    const { deviceId, currentlyActive } = toggleConfirm;
    setToggleConfirm(null);
    const action = currentlyActive ? 'deactivate' : 'reactivate';

    setDeactivatingDeviceId(deviceId);
    setError(null);
    setSuccess(null);

    try {
      const response = await authFetch(`/api/v1/retailer-admin/devices/${deviceId}`, accessToken, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ active: !currentlyActive }),
      });

      const data = await safeJson(response) as DeviceUpdateResponse | null;

      if (response.ok && data?.success) {
        setSuccess(`Device ${currentlyActive ? 'deactivated' : 'reactivated'} successfully.`);
        // Reload devices list
        loadDevices();
      } else {
        setError(data?.error?.message || `Failed to ${action} device.`);
      }
    } catch (err: any) {
      logger.error('Device toggle error:', err);
      setError(err.message || 'Network error. Please check your connection.');
    } finally {
      setDeactivatingDeviceId(null);
    }
  };

  return (
    <div className="pay-container">
      {/* UIUX-RET-002: Styled confirmation modal for device toggle */}
      <Modal
        isOpen={!!toggleConfirm}
        onClose={() => setToggleConfirm(null)}
        title={toggleConfirm?.currentlyActive ? 'Deactivate Device' : 'Reactivate Device'}
        actions={
          <>
            <button className="btn-secondary" onClick={() => setToggleConfirm(null)}>Cancel</button>
            <button className="btn-danger" onClick={confirmToggleDevice}>
              {toggleConfirm?.currentlyActive ? 'Deactivate' : 'Reactivate'}
            </button>
          </>
        }
      >
        <p className="modal-confirm-text">
          {toggleConfirm?.currentlyActive
            ? 'Are you sure you want to deactivate this device? The device will need to be re-enrolled to use the POS again.'
            : 'Are you sure you want to reactivate this device?'}
        </p>
      </Modal>

      {/* T-112: Breadcrumb navigation */}
      <Breadcrumb items={[{ label: 'Home', path: `/s/${storeCode}` }, { label: 'Devices' }]} />
      {/* Header */}
      <div className="pay-header">
        <h1 className="pay-title">
          Device Activation
        </h1>
        <p className="pay-subtitle">
          Activate POS devices to connect them to your store: {store?.name}
        </p>
      </div>

      {/* Success Message */}
      {success && (
        <div className="pay-alert-success">
          <span className="pay-alert-icon">&#10003;</span>
          {success}
        </div>
      )}

      {/* Error Message */}
      {error && (
        <div className="pay-alert-error">
          <span className="pay-alert-icon">&#10007;</span>
          {error}
        </div>
      )}

      {/* Activation Form */}
      <section className="card dact-section dact-section--mb">
        <h2 className="pay-section-title">
          <span className="pay-section-icon">&#128241;</span>
          Activate New Device
        </h2>

        <div style={{ marginBottom: '1rem' }}>
          <label className="pay-bank-label">
            Activation Code
          </label>
          <input
            className={`form-input dact-code-input${error ? ' dact-code-input--error' : ''}`}
            type="text"
            value={activationCode}
            onChange={handleCodeChange}
            placeholder="SM-XXXX-XX"
            maxLength={12}
          />
          <p className="dact-hint">
            Enter the 6-character code displayed on your POS device
          </p>
        </div>

        <button
          onClick={handleActivate}
          disabled={activating || !isValidCode(activationCode)}
          className="dact-activate-btn"
        >
          {activating ? 'Activating...' : 'Activate Device'}
        </button>

        {/* Instructions */}
        <div className="dact-instructions">
          <h4 className="dact-instructions-title">
            How to get an activation code:
          </h4>
          <ol className="dact-instructions-list">
            <li>Open the SuperMandi POS app on your device</li>
            <li>Tap "Connect Store" or go to Settings &gt; Device</li>
            <li>An activation code (SM-XXXX-XX) will be displayed</li>
            <li>Enter that code above within 15 minutes</li>
          </ol>
        </div>
      </section>

      {/* Connected Devices List */}
      <section className="card dact-section">
        <div className="flex-between grid-mb">
          <h2 className="pay-section-title">
            <span className="pay-section-icon">&#128279;</span>
            Connected Devices
          </h2>
          <button
            onClick={loadDevices}
            disabled={loadingDevices}
            className="btn btn-secondary btn-sm"
          >
            {loadingDevices ? 'Loading...' : 'Refresh'}
          </button>
        </div>

        {loadingDevices && devices.length === 0 ? (
          <div className="text-center-muted">
            Loading devices...
          </div>
        ) : devices.length === 0 ? (
          <div className="dact-devices-empty">
            <span className="dact-devices-empty-icon">&#128241;</span>
            No devices connected yet.<br />
            Use the activation code above to connect your first device.
          </div>
        ) : (
          <div className="dact-device-list">
            {devices.map((device) => (
              <div
                key={device.id}
                className="dact-device-card"
                style={{ border: `1px solid ${device.isActive ? 'var(--border)' : '#fca5a5'}` }}
              >
                <div>
                  <div className="dact-device-name">
                    {device.label || 'POS Device'}
                    {device.isActive ? (
                      <span className="dact-badge-active">ACTIVE</span>
                    ) : (
                      <span className="dact-badge-revoked">REVOKED</span>
                    )}
                  </div>
                  <div className="dact-device-meta">
                    {device.manufacturer && device.model
                      ? `${device.manufacturer} ${device.model}`
                      : device.deviceType}
                    {device.appVersion && ` | v${device.appVersion}`}
                  </div>
                  <div className="dact-device-timestamp">
                    Added: {new Date(device.createdAt).toLocaleDateString()}
                    {device.lastSeen && ` | Last seen: ${new Date(device.lastSeen).toLocaleString()}`}
                  </div>
                </div>
                <div className="dact-device-actions">
                  <div className="dact-device-id">
                    {device.id.substring(0, 8)}...
                  </div>
                  {/* RET-AUD-027: Deactivate/Reactivate button */}
                  <button
                    onClick={() => handleToggleDevice(device.id, device.isActive)}
                    disabled={deactivatingDeviceId === device.id}
                    className={device.isActive ? 'btn btn-danger-light btn-xs' : 'btn btn-xs'}
                    style={{
                      background: device.isActive ? undefined : '#dcfce7',
                      color: device.isActive ? undefined : '#166534',
                      border: device.isActive ? undefined : '1px solid #86efac',
                      opacity: deactivatingDeviceId === device.id ? 0.6 : 1,
                    }}
                  >
                    {deactivatingDeviceId === device.id
                      ? 'Processing...'
                      : device.isActive
                        ? 'Deactivate'
                        : 'Reactivate'}
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
