// RET-WEB-002: Device Activation Page
// Allows retailers to activate POS devices using activation codes
// Activation code format: SM-XXXX-XX (generated by POS app)

import { useState, useCallback, useEffect } from 'react';
import { useParams } from 'react-router-dom';
import { useAuth } from '../lib/AuthContext';
import { authFetch, safeJson } from '../lib/api';
// T-112: Breadcrumb navigation
import Breadcrumb from '../components/Breadcrumb';
// UIUX-RET-002: Styled modal instead of window.confirm
import Modal from '../components/Modal';

interface Device {
  id: string;
  fingerprint: string;
  label: string;
  deviceType: string;
  manufacturer?: string;
  model?: string;
  appVersion?: string;
  lastSeen?: string;
  createdAt: string;
  isActive: boolean;
}

// RET-AUD-027: Device deactivation response
interface DeviceUpdateResponse {
  success: boolean;
  device?: Device;
  error?: { code: string; message: string };
}

export default function DeviceActivationPage() {
  const { storeCode } = useParams<{ storeCode: string }>();
  const { accessToken, store } = useAuth();

  // Form state
  const [activationCode, setActivationCode] = useState('');
  const [devices, setDevices] = useState<Device[]>([]);
  const [loadingDevices, setLoadingDevices] = useState(false);
  const [devicesLoaded, setDevicesLoaded] = useState(false);

  // UI state
  const [activating, setActivating] = useState(false);
  const [deactivatingDeviceId, setDeactivatingDeviceId] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  // UIUX-RET-002: Styled confirmation modal for device toggle
  const [toggleConfirm, setToggleConfirm] = useState<{ deviceId: string; currentlyActive: boolean } | null>(null);

  // Format activation code as user types (SM-XXXX-XX)
  const formatActivationCode = useCallback((value: string): string => {
    // Remove all non-alphanumeric except hyphens
    const cleaned = value.toUpperCase().replace(/[^A-Z0-9-]/g, '');

    // If starts with SM-, keep it
    if (cleaned.startsWith('SM-')) {
      const rest = cleaned.substring(3).replace(/-/g, '');
      if (rest.length <= 4) {
        return `SM-${rest}`;
      } else if (rest.length <= 6) {
        return `SM-${rest.substring(0, 4)}-${rest.substring(4)}`;
      } else {
        return `SM-${rest.substring(0, 4)}-${rest.substring(4, 6)}`;
      }
    }

    // Auto-add SM- prefix if user types alphanumeric
    const alphaNum = cleaned.replace(/-/g, '');
    if (alphaNum.length === 0) return '';
    if (alphaNum.length <= 4) {
      return `SM-${alphaNum}`;
    } else if (alphaNum.length <= 6) {
      return `SM-${alphaNum.substring(0, 4)}-${alphaNum.substring(4)}`;
    } else {
      return `SM-${alphaNum.substring(0, 4)}-${alphaNum.substring(4, 6)}`;
    }
  }, []);

  // Handle code input change
  const handleCodeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const formatted = formatActivationCode(e.target.value);
    setActivationCode(formatted);
    setError(null);
    setSuccess(null);
  };

  // Validate activation code format
  const isValidCode = (code: string): boolean => {
    return /^SM-[A-Z0-9]{4}-[A-Z0-9]{2}$/.test(code);
  };

  // Load devices for this store
  // #184.19: Handle 401 and show error messages
  const loadDevices = useCallback(async () => {
    if (!accessToken) return;

    setLoadingDevices(true);
    setError(null);
    try {
      const response = await authFetch('/api/v1/retailer-admin/devices', accessToken);
      if (response.ok) {
        const data = await safeJson(response);
        setDevices(data.devices || []);
      } else if (response.status === 401) {
        setError('Session expired. Please log in again.');
      } else {
        const data = await safeJson(response);
        setError(data?.error?.message || `Failed to load devices (${response.status})`);
      }
    } catch (err) {
      console.error('Failed to load devices:', err);
      setError(err instanceof Error && err.name === 'AbortError'
        ? 'Request timed out. Please try again.'
        : 'Network error loading devices. Please check your connection.');
    } finally {
      setLoadingDevices(false);
      setDevicesLoaded(true);
    }
  }, [accessToken]);

  // AUDIT-RET-030: Fix useState anti-pattern — use useEffect for side effects
  useEffect(() => {
    if (accessToken && !devicesLoaded) {
      loadDevices();
    }
  }, [accessToken, devicesLoaded]);

  // Handle activation
  const handleActivate = async () => {
    if (!accessToken || !isValidCode(activationCode)) return;

    setActivating(true);
    setError(null);
    setSuccess(null);

    try {
      const response = await authFetch('/api/v1/retailer-admin/devices/activate', accessToken, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ activation_code: activationCode }),
      });

      const data = await safeJson(response);

      if (response.ok && data.success) {
        setSuccess(`Device activated successfully! Device ID: ${data.device_id.substring(0, 8)}...`);
        setActivationCode('');
        // Reload devices list
        loadDevices();
      } else {
        // Handle specific error codes
        const errorCode = data.error?.code;
        switch (errorCode) {
          case 'CODE_NOT_FOUND':
            setError('Activation code not found. Please check the code and try again.');
            break;
          case 'CODE_ALREADY_USED':
            setError('This activation code has already been used.');
            break;
          case 'CODE_EXPIRED':
            setError('This activation code has expired. Please generate a new code on the POS device.');
            break;
          case 'VALIDATION_ERROR':
            setError(data.error?.message || 'Invalid activation code format.');
            break;
          default:
            setError(data.error?.message || 'Failed to activate device. Please try again.');
        }
      }
    } catch (err: any) {
      console.error('Device activation error:', err);
      setError(err.message || 'Network error. Please check your connection.');
    } finally {
      setActivating(false);
    }
  };

  // RET-AUD-027: Handle device deactivation/reactivation
  // UIUX-RET-002: Show styled Modal instead of window.confirm
  const handleToggleDevice = async (deviceId: string, currentlyActive: boolean) => {
    if (!accessToken) return;

    setToggleConfirm({ deviceId, currentlyActive });
  };

  const confirmToggleDevice = async () => {
    if (!toggleConfirm || !accessToken) return;
    const { deviceId, currentlyActive } = toggleConfirm;
    setToggleConfirm(null);
    const action = currentlyActive ? 'deactivate' : 'reactivate';

    setDeactivatingDeviceId(deviceId);
    setError(null);
    setSuccess(null);

    try {
      const response = await authFetch(`/api/v1/retailer-admin/devices/${deviceId}`, accessToken, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ active: !currentlyActive }),
      });

      const data = await safeJson(response) as DeviceUpdateResponse | null;

      if (response.ok && data?.success) {
        setSuccess(`Device ${currentlyActive ? 'deactivated' : 'reactivated'} successfully.`);
        // Reload devices list
        loadDevices();
      } else {
        setError(data?.error?.message || `Failed to ${action} device.`);
      }
    } catch (err: any) {
      console.error('Device toggle error:', err);
      setError(err.message || 'Network error. Please check your connection.');
    } finally {
      setDeactivatingDeviceId(null);
    }
  };

  return (
    <div style={{
      minHeight: '100%',
      background: 'linear-gradient(180deg, #f0f9ff 0%, #f8fafc 100%)',
      padding: '2rem',
    }}>
      {/* UIUX-RET-002: Styled confirmation modal for device toggle */}
      <Modal
        isOpen={!!toggleConfirm}
        onClose={() => setToggleConfirm(null)}
        title={toggleConfirm?.currentlyActive ? 'Deactivate Device' : 'Reactivate Device'}
        actions={
          <>
            <button className="btn-secondary" onClick={() => setToggleConfirm(null)}>Cancel</button>
            <button className="btn-danger" onClick={confirmToggleDevice}>
              {toggleConfirm?.currentlyActive ? 'Deactivate' : 'Reactivate'}
            </button>
          </>
        }
      >
        <p style={{ color: '#475569', fontSize: '0.9rem', lineHeight: 1.5 }}>
          {toggleConfirm?.currentlyActive
            ? 'Are you sure you want to deactivate this device? The device will need to be re-enrolled to use the POS again.'
            : 'Are you sure you want to reactivate this device?'}
        </p>
      </Modal>

      {/* T-112: Breadcrumb navigation */}
      <Breadcrumb items={[{ label: 'Home', path: `/s/${storeCode}` }, { label: 'Devices' }]} />
      {/* Header */}
      <div style={{ marginBottom: '2rem' }}>
        <h1 style={{
          margin: '0 0 0.5rem',
          fontSize: '1.75rem',
          fontWeight: '700',
          color: '#1e293b',
        }}>
          Device Activation
        </h1>
        <p style={{
          margin: 0,
          fontSize: '0.95rem',
          color: '#64748b',
        }}>
          Activate POS devices to connect them to your store: {store?.name}
        </p>
      </div>

      {/* Success Message */}
      {success && (
        <div style={{
          padding: '1rem 1.25rem',
          background: '#dcfce7',
          borderRadius: '10px',
          border: '1px solid #22c55e',
          color: '#166534',
          marginBottom: '1.5rem',
          display: 'flex',
          alignItems: 'center',
          gap: '0.75rem',
          fontSize: '0.95rem',
        }}>
          <span style={{ fontSize: '1.25rem' }}>&#10003;</span>
          {success}
        </div>
      )}

      {/* Error Message */}
      {error && (
        <div style={{
          padding: '1rem 1.25rem',
          background: '#fee2e2',
          borderRadius: '10px',
          border: '1px solid #ef4444',
          color: '#dc2626',
          marginBottom: '1.5rem',
          display: 'flex',
          alignItems: 'center',
          gap: '0.75rem',
          fontSize: '0.95rem',
        }}>
          <span style={{ fontSize: '1.25rem' }}>&#10007;</span>
          {error}
        </div>
      )}

      {/* Activation Form */}
      <section style={{
        background: 'white',
        borderRadius: '16px',
        padding: '1.5rem',
        boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
        border: '1px solid #e2e8f0',
        marginBottom: '1.5rem',
      }}>
        <h2 style={{
          margin: '0 0 1.25rem',
          fontSize: '1rem',
          fontWeight: '600',
          color: '#334155',
          display: 'flex',
          alignItems: 'center',
          gap: '0.5rem',
        }}>
          <span style={{ fontSize: '1.2rem' }}>&#128241;</span>
          Activate New Device
        </h2>

        <div style={{ marginBottom: '1rem' }}>
          <label style={{
            display: 'block',
            fontSize: '0.85rem',
            fontWeight: '500',
            color: '#475569',
            marginBottom: '0.5rem',
          }}>
            Activation Code
          </label>
          <input
            type="text"
            value={activationCode}
            onChange={handleCodeChange}
            placeholder="SM-XXXX-XX"
            maxLength={12}
            style={{
              width: '100%',
              maxWidth: '250px',
              padding: '0.75rem 1rem',
              fontSize: '1.25rem',
              fontFamily: 'monospace',
              fontWeight: '600',
              letterSpacing: '0.1em',
              border: `1px solid ${error ? '#ef4444' : '#e2e8f0'}`,
              borderRadius: '10px',
              outline: 'none',
              boxSizing: 'border-box',
              textAlign: 'center',
              textTransform: 'uppercase',
            }}
            onFocus={(e) => e.currentTarget.style.borderColor = '#3b82f6'}
            onBlur={(e) => e.currentTarget.style.borderColor = error ? '#ef4444' : '#e2e8f0'}
          />
          <p style={{ margin: '0.5rem 0 0', fontSize: '0.8rem', color: '#94a3b8' }}>
            Enter the 6-character code displayed on your POS device
          </p>
        </div>

        <button
          onClick={handleActivate}
          disabled={activating || !isValidCode(activationCode)}
          style={{
            padding: '0.875rem 2rem',
            background: activating || !isValidCode(activationCode)
              ? '#94a3b8'
              : 'linear-gradient(135deg, #22c55e 0%, #16a34a 100%)',
            color: 'white',
            border: 'none',
            borderRadius: '10px',
            fontSize: '1rem',
            fontWeight: '600',
            cursor: activating || !isValidCode(activationCode) ? 'not-allowed' : 'pointer',
            boxShadow: activating || !isValidCode(activationCode)
              ? 'none'
              : '0 4px 14px rgba(34, 197, 94, 0.35)',
            transition: 'all 0.2s',
          }}
        >
          {activating ? 'Activating...' : 'Activate Device'}
        </button>

        {/* Instructions */}
        <div style={{
          marginTop: '1.5rem',
          padding: '1rem',
          background: '#f8fafc',
          borderRadius: '8px',
          border: '1px solid #e2e8f0',
        }}>
          <h4 style={{ margin: '0 0 0.5rem', fontSize: '0.85rem', color: '#475569' }}>
            How to get an activation code:
          </h4>
          <ol style={{ margin: 0, paddingLeft: '1.25rem', fontSize: '0.8rem', color: '#64748b', lineHeight: '1.6' }}>
            <li>Open the SuperMandi POS app on your device</li>
            <li>Tap "Connect Store" or go to Settings &gt; Device</li>
            <li>An activation code (SM-XXXX-XX) will be displayed</li>
            <li>Enter that code above within 15 minutes</li>
          </ol>
        </div>
      </section>

      {/* Connected Devices List */}
      <section style={{
        background: 'white',
        borderRadius: '16px',
        padding: '1.5rem',
        boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
        border: '1px solid #e2e8f0',
      }}>
        <div style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: '1rem',
        }}>
          <h2 style={{
            margin: 0,
            fontSize: '1rem',
            fontWeight: '600',
            color: '#334155',
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem',
          }}>
            <span style={{ fontSize: '1.2rem' }}>&#128279;</span>
            Connected Devices
          </h2>
          <button
            onClick={loadDevices}
            disabled={loadingDevices}
            style={{
              padding: '0.5rem 1rem',
              background: 'transparent',
              border: '1px solid #e2e8f0',
              borderRadius: '6px',
              fontSize: '0.8rem',
              color: '#64748b',
              cursor: loadingDevices ? 'not-allowed' : 'pointer',
            }}
          >
            {loadingDevices ? 'Loading...' : 'Refresh'}
          </button>
        </div>

        {loadingDevices && devices.length === 0 ? (
          <div style={{ padding: '2rem', textAlign: 'center', color: '#94a3b8' }}>
            Loading devices...
          </div>
        ) : devices.length === 0 ? (
          <div style={{
            padding: '2rem',
            textAlign: 'center',
            color: '#94a3b8',
            background: '#f8fafc',
            borderRadius: '8px',
          }}>
            <span style={{ fontSize: '2rem', display: 'block', marginBottom: '0.5rem' }}>&#128241;</span>
            No devices connected yet.<br />
            Use the activation code above to connect your first device.
          </div>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {devices.map((device) => (
              <div
                key={device.id}
                style={{
                  padding: '1rem',
                  background: '#f8fafc',
                  borderRadius: '10px',
                  border: `1px solid ${device.isActive ? '#e2e8f0' : '#fca5a5'}`,
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'center',
                }}
              >
                <div>
                  <div style={{
                    fontSize: '0.95rem',
                    fontWeight: '500',
                    color: '#1e293b',
                    marginBottom: '0.25rem',
                  }}>
                    {device.label || 'POS Device'}
                    {device.isActive ? (
                      <span style={{
                        marginLeft: '0.5rem',
                        padding: '0.125rem 0.5rem',
                        background: '#dcfce7',
                        color: '#166534',
                        borderRadius: '4px',
                        fontSize: '0.7rem',
                        fontWeight: '600',
                      }}>ACTIVE</span>
                    ) : (
                      <span style={{
                        marginLeft: '0.5rem',
                        padding: '0.125rem 0.5rem',
                        background: '#fee2e2',
                        color: '#dc2626',
                        borderRadius: '4px',
                        fontSize: '0.7rem',
                        fontWeight: '600',
                      }}>REVOKED</span>
                    )}
                  </div>
                  <div style={{ fontSize: '0.75rem', color: '#64748b' }}>
                    {device.manufacturer && device.model
                      ? `${device.manufacturer} ${device.model}`
                      : device.deviceType}
                    {device.appVersion && ` | v${device.appVersion}`}
                  </div>
                  <div style={{ fontSize: '0.7rem', color: '#94a3b8', marginTop: '0.25rem' }}>
                    Added: {new Date(device.createdAt).toLocaleDateString()}
                    {device.lastSeen && ` | Last seen: ${new Date(device.lastSeen).toLocaleString()}`}
                  </div>
                </div>
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '0.5rem' }}>
                  <div style={{
                    fontSize: '0.7rem',
                    color: '#94a3b8',
                    fontFamily: 'monospace',
                  }}>
                    {device.id.substring(0, 8)}...
                  </div>
                  {/* RET-AUD-027: Deactivate/Reactivate button */}
                  <button
                    onClick={() => handleToggleDevice(device.id, device.isActive)}
                    disabled={deactivatingDeviceId === device.id}
                    style={{
                      padding: '0.375rem 0.75rem',
                      background: device.isActive ? '#fee2e2' : '#dcfce7',
                      color: device.isActive ? '#dc2626' : '#166534',
                      border: `1px solid ${device.isActive ? '#fca5a5' : '#86efac'}`,
                      borderRadius: '6px',
                      fontSize: '0.7rem',
                      fontWeight: '500',
                      cursor: deactivatingDeviceId === device.id ? 'not-allowed' : 'pointer',
                      opacity: deactivatingDeviceId === device.id ? 0.6 : 1,
                    }}
                  >
                    {deactivatingDeviceId === device.id
                      ? 'Processing...'
                      : device.isActive
                        ? 'Deactivate'
                        : 'Reactivate'}
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </section>
    </div>
  );
}
