#!/usr/bin/env bash
# =============================================================================
# ZRP-B-026, B-027, B-028: License Policy, Test Coverage, Flaky Detection
# =============================================================================
set -euo pipefail

PASS=0
FAIL=0
WARN=0

gate_pass() { PASS=$((PASS + 1)); echo "  PASS: $1 — $2"; }
gate_fail() { FAIL=$((FAIL + 1)); echo "  FAIL: $1 — $2: $3"; }
gate_warn() { WARN=$((WARN + 1)); echo "  WARN: $1 — $2: $3"; }

echo "=== ZRP-B-026/027/028: License, Coverage, Flaky Detection ==="
echo ""

# =============================================================================
# ZRP-B-026: License policy — detect copyleft licenses (BLOCKING P1)
# =============================================================================
echo "--- ZRP-B-026: License policy (copyleft detection) ---"

POLICY_FILE=".license-policy.json"
BLOCKED_LICENSES=("GPL-2.0" "GPL-3.0" "AGPL-3.0" "SSPL-1.0" "GPL-2.0-only" "GPL-3.0-only" "AGPL-3.0-only")

LICENSE_VIOLATIONS=0
PROJECTS=("backend" "retailer-admin" "supplier-portal" "supermandi-superadmin")

for project in "${PROJECTS[@]}"; do
  if [ ! -f "$project/pnpm-lock.yaml" ] && [ ! -f "$project/package-lock.json" ]; then
    echo "  SKIP: $project (no lockfile)"
    continue
  fi

  # Use pnpm licenses list if available, fallback to scanning node_modules
  if [ -d "$project/node_modules" ]; then
    # Scan package.json files in node_modules for license fields
    FOUND_COPYLEFT=0
    for blocked in "${BLOCKED_LICENSES[@]}"; do
      MATCHES=$(grep -rl "\"license\": \"$blocked\"" "$project/node_modules/" 2>/dev/null | head -5 || echo "")
      if [ -n "$MATCHES" ]; then
        COUNT=$(echo "$MATCHES" | wc -l)
        echo "  ALERT: $project has $COUNT package(s) with $blocked license"
        echo "$MATCHES" | head -3 | while read -r f; do
          PKG=$(echo "$f" | sed 's|.*/node_modules/||;s|/package.json||')
          echo "    - $PKG"
        done
        FOUND_COPYLEFT=$((FOUND_COPYLEFT + COUNT))
      fi
    done
    if [ "$FOUND_COPYLEFT" -gt 0 ]; then
      LICENSE_VIOLATIONS=$((LICENSE_VIOLATIONS + FOUND_COPYLEFT))
    else
      echo "  OK: $project — no copyleft licenses detected"
    fi
  else
    # No node_modules — check lockfile for known copyleft packages
    for blocked in "${BLOCKED_LICENSES[@]}"; do
      if grep -qi "$blocked" "$project/pnpm-lock.yaml" 2>/dev/null || \
         grep -qi "$blocked" "$project/package-lock.json" 2>/dev/null; then
        echo "  ALERT: $project lockfile references $blocked"
        LICENSE_VIOLATIONS=$((LICENSE_VIOLATIONS + 1))
      fi
    done
    if [ "$LICENSE_VIOLATIONS" -eq 0 ]; then
      echo "  OK: $project — no copyleft references in lockfile"
    fi
  fi
done

if [ "$LICENSE_VIOLATIONS" -eq 0 ]; then
  gate_pass "ZRP-B-026" "No copyleft licenses detected"
else
  gate_fail "ZRP-B-026" "License policy" "$LICENSE_VIOLATIONS copyleft license violation(s)"
fi

# =============================================================================
# ZRP-B-027: Test coverage floor (BLOCKING P1)
# =============================================================================
echo ""
echo "--- ZRP-B-027: Test coverage floor ---"

COVERAGE_BASELINE=".coverage-baseline.json"
if [ -f "$COVERAGE_BASELINE" ]; then
  THRESHOLD=$(grep -oP '"global":\s*\K[0-9]+' "$COVERAGE_BASELINE" 2>/dev/null || echo "0")
else
  THRESHOLD=0
fi

if [ "$THRESHOLD" -gt 0 ]; then
  # Check if coverage report exists (generated by test job)
  COVERAGE_FILE="backend/coverage/coverage-summary.json"
  if [ -f "$COVERAGE_FILE" ]; then
    ACTUAL=$(grep -oP '"lines":\s*\{\s*"total":\s*[0-9]+,\s*"covered":\s*[0-9]+,\s*"skipped":\s*[0-9]+,\s*"pct":\s*\K[0-9.]+' "$COVERAGE_FILE" 2>/dev/null | head -1 || echo "0")
    ACTUAL_INT=$(echo "$ACTUAL" | awk '{printf "%.0f", $1}')
    if [ "$ACTUAL_INT" -ge "$THRESHOLD" ]; then
      gate_pass "ZRP-B-027" "Coverage ${ACTUAL}% >= ${THRESHOLD}% threshold"
    else
      gate_fail "ZRP-B-027" "Test coverage" "Coverage ${ACTUAL}% < ${THRESHOLD}% threshold"
    fi
  else
    # Coverage report not generated — check if jest is configured for coverage
    if grep -q '"coverage"' backend/package.json 2>/dev/null || \
       grep -q 'collectCoverage' backend/jest.config.ts 2>/dev/null; then
      gate_warn "ZRP-B-027" "Coverage" "Coverage configured but report not found (run tests with --coverage)"
    else
      gate_warn "ZRP-B-027" "Coverage" "Coverage not yet configured in test pipeline"
    fi
  fi
else
  gate_warn "ZRP-B-027" "Coverage" "No coverage threshold set in $COVERAGE_BASELINE"
fi

# =============================================================================
# ZRP-B-028: Flaky test quarantine — detect retry patterns (WARNING P2)
# =============================================================================
echo ""
echo "--- ZRP-B-028: Flaky test detection ---"

FLAKY_PATTERNS=0
# Scan test files for retry patterns that indicate flaky tests
RETRY_FILES=$(grep -rl "jest.retryTimes\|retryTimes\|retry:" backend/ retailer-admin/ supplier-portal/ supermandi-superadmin/ 2>/dev/null | grep -E '\.(test|spec)\.(ts|tsx|js|jsx)$' || echo "")

if [ -n "$RETRY_FILES" ]; then
  FLAKY_PATTERNS=$(echo "$RETRY_FILES" | wc -l)
  echo "  Found $FLAKY_PATTERNS test file(s) with retry patterns:"
  echo "$RETRY_FILES" | head -5 | while read -r f; do echo "    - $f"; done
  gate_warn "ZRP-B-028" "Flaky tests" "$FLAKY_PATTERNS file(s) use retryTimes (may indicate flakiness)"
else
  gate_pass "ZRP-B-028" "No retry patterns in test files"
fi

# =============================================================================
# SUMMARY
# =============================================================================
echo ""
echo "==============================================================="
echo "ZRP License & Coverage Summary: $PASS PASS, $FAIL FAIL, $WARN WARN"
echo "==============================================================="

echo "ZRP_LICENSE_PASS=$PASS" >> "${GITHUB_ENV:-/dev/null}" 2>/dev/null || true
echo "ZRP_LICENSE_FAIL=$FAIL" >> "${GITHUB_ENV:-/dev/null}" 2>/dev/null || true
echo "ZRP_LICENSE_WARN=$WARN" >> "${GITHUB_ENV:-/dev/null}" 2>/dev/null || true

if [ "$FAIL" -gt 0 ]; then
  echo ""
  echo "BLOCKED: $FAIL license/coverage gate(s) failed."
  exit 1
fi

echo ""
echo "License & Coverage: All blocking gates passed."
exit 0
