#!/usr/bin/env bash
# =============================================================================
# ZRP Parity Report Generator
# Aggregates all gate results and generates GitHub Step Summary.
# Called at the end of CI and CD pipelines.
# =============================================================================
set -euo pipefail

REPORT_TYPE="${1:-ci}"  # "ci" or "cd"

echo "=== ZRP Parity Report ($REPORT_TYPE) ==="
echo ""

# Read gate results from environment (set by individual gate scripts)
ZRP_A_PASS=${ZRP_A_PASS:-0}
ZRP_A_FAIL=${ZRP_A_FAIL:-0}
ZRP_A_WARN=${ZRP_A_WARN:-0}
ZRP_SECURITY_PASS=${ZRP_SECURITY_PASS:-0}
ZRP_SECURITY_FAIL=${ZRP_SECURITY_FAIL:-0}
ZRP_MIGRATION_PASS=${ZRP_MIGRATION_PASS:-0}
ZRP_MIGRATION_FAIL=${ZRP_MIGRATION_FAIL:-0}
ZRP_CONFIG_PASS=${ZRP_CONFIG_PASS:-0}
ZRP_CONFIG_FAIL=${ZRP_CONFIG_FAIL:-0}
ZRP_BUNDLE_PASS=${ZRP_BUNDLE_PASS:-0}
ZRP_BUNDLE_FAIL=${ZRP_BUNDLE_FAIL:-0}
ZRP_DOCKER_PASS=${ZRP_DOCKER_PASS:-0}
ZRP_DOCKER_FAIL=${ZRP_DOCKER_FAIL:-0}

TOTAL_PASS=$((ZRP_A_PASS + ZRP_SECURITY_PASS + ZRP_MIGRATION_PASS + ZRP_CONFIG_PASS + ZRP_BUNDLE_PASS + ZRP_DOCKER_PASS))
TOTAL_FAIL=$((ZRP_A_FAIL + ZRP_SECURITY_FAIL + ZRP_MIGRATION_FAIL + ZRP_CONFIG_FAIL + ZRP_BUNDLE_FAIL + ZRP_DOCKER_FAIL))
TOTAL=$((TOTAL_PASS + TOTAL_FAIL))

# Generate console output
echo "┌─────────────────────────┬──────┬──────┬──────┐"
echo "│ Category                │ PASS │ FAIL │ WARN │"
echo "├─────────────────────────┼──────┼──────┼──────┤"
printf "│ A: Git Discipline       │ %4d │ %4d │ %4d │\n" "$ZRP_A_PASS" "$ZRP_A_FAIL" "$ZRP_A_WARN"
printf "│ B+F: Security Audit     │ %4d │ %4d │    0 │\n" "$ZRP_SECURITY_PASS" "$ZRP_SECURITY_FAIL"
printf "│ E: Migration Safety     │ %4d │ %4d │    0 │\n" "$ZRP_MIGRATION_PASS" "$ZRP_MIGRATION_FAIL"
printf "│ D: Config Parity        │ %4d │ %4d │    0 │\n" "$ZRP_CONFIG_PASS" "$ZRP_CONFIG_FAIL"
printf "│ B: Bundle Size          │ %4d │ %4d │    0 │\n" "$ZRP_BUNDLE_PASS" "$ZRP_BUNDLE_FAIL"
printf "│ B: Dockerfile Lint      │ %4d │ %4d │    0 │\n" "$ZRP_DOCKER_PASS" "$ZRP_DOCKER_FAIL"
echo "├─────────────────────────┼──────┼──────┼──────┤"
printf "│ TOTAL                   │ %4d │ %4d │ %4d │\n" "$TOTAL_PASS" "$TOTAL_FAIL" "$ZRP_A_WARN"
echo "└─────────────────────────┴──────┴──────┴──────┘"

# Generate GitHub Step Summary if available
if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  {
    echo "## ZRP Parity Report ($REPORT_TYPE)"
    echo ""
    echo "| Category | PASS | FAIL | WARN |"
    echo "|----------|------|------|------|"
    echo "| A: Git Discipline | $ZRP_A_PASS | $ZRP_A_FAIL | $ZRP_A_WARN |"
    echo "| B+F: Security Audit | $ZRP_SECURITY_PASS | $ZRP_SECURITY_FAIL | 0 |"
    echo "| E: Migration Safety | $ZRP_MIGRATION_PASS | $ZRP_MIGRATION_FAIL | 0 |"
    echo "| D: Config Parity | $ZRP_CONFIG_PASS | $ZRP_CONFIG_FAIL | 0 |"
    echo "| B: Bundle Size | $ZRP_BUNDLE_PASS | $ZRP_BUNDLE_FAIL | 0 |"
    echo "| B: Dockerfile Lint | $ZRP_DOCKER_PASS | $ZRP_DOCKER_FAIL | 0 |"
    echo "| **TOTAL** | **$TOTAL_PASS** | **$TOTAL_FAIL** | **$ZRP_A_WARN** |"
    echo ""
    if [ "$TOTAL_FAIL" -eq 0 ]; then
      echo "### Verdict: PASS — All $TOTAL_PASS gates passed"
    else
      echo "### Verdict: FAIL — $TOTAL_FAIL gate(s) failed out of $TOTAL"
    fi
    echo ""
    echo "*Generated by ZRP Parity Report v1.0*"
  } >> "$GITHUB_STEP_SUMMARY"
  echo ""
  echo "GitHub Step Summary written."
fi

echo ""
if [ "$TOTAL_FAIL" -eq 0 ]; then
  echo "ZRP VERDICT: PASS ($TOTAL_PASS/$TOTAL gates passed)"
  exit 0
else
  echo "ZRP VERDICT: FAIL ($TOTAL_FAIL/$TOTAL gates failed)"
  exit 1
fi
